---
title: "BETA MODELS GLMM BETA_FAMILY LINK = LOGIT"
output: html_document
date: "2025-05-08"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading packages, warning=FALSE, results='hide', message=FALSE}
library("formatR")
library("foreign")
library("ggplot2")
library("lme4")
library("poLCA")
library("reprex")
library("tidyr")
library("klippy")
library("dplyr")
library("haven")
library("psych")
library("Matrix")
library("lme4")
library("merTools")
library("sjPlot")
library("glmmTMB")
library("foreign")
library("gt")
library("tibble")
library("dplyr")
library("sjPlot")
library("tidyverse")
library("broom.mixed")
```

```{r loading data, results='hide', warning=FALSE, message=FALSE}
NEA2022 <- readRDS("data/processed/LCAfinal.rds")

attach(NEA2022)
set.seed(123)
```


```{r transform in factor, cache=TRUE}
#Transform in factor
NEA2022 <- NEA2022 %>%
  mutate(
    migration = trimws(migration),
    education = trimws(education),
    gender = trimws(gender),
    leeftijd = trimws(leeftijd)
  )

NEA2022$gender <- factor(NEA2022$gender, levels = c("m", "v"))
NEA2022$migration <- factor(NEA2022$migration,
                            levels = c("nl", "eu", "noeu"))
NEA2022$education <- factor(NEA2022$education,
                            levels = c("laag", "middel", "hoog"))
NEA2022$leeftijd <- factor(NEA2022$leeftijd,
                            levels = c("15.35", "35.55", "55.75"))
```


<br><br>


# Overall unsafety (class 6)


<br><br>


```{r regression overall unsafety, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv6 = pmodel7_empv6)

NEA2022$pmodel7_empv6_T <- (NEA2022$pmodel7_empv6 * (29923 - 1) + 0.5) / 29923

flb_6_0 <- glmmTMB(pmodel7_empv6_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_6_1 <- glmmTMB(pmodel7_empv6_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_6_0)
summary(flb_6_1)

tidy(flb_6_1, effects = "fixed", conf.int = TRUE)
```


```{r Calculation ICC overall unsafe, cache=TRUE}

mu <- fitted(flb_6_0)
var_y <- mu * (1 - mu) / (1 + 2.73)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 0.0008979/(0.0008979+0.01190397), "\n",
    "ICC final: ", 1.939e-09/(1.939e-09+0.01190397), "\n",
    "PCV: ", (0.0008979-1.939e-09)/0.0008979, "\n")
```


```{r Model1: Predicted probability overall unsafety, cache=TRUE}
NEA2022$predicted_6 <- predict(flb_6_1, re.form = NULL, type = "response")

NEA2022$residual_6 <- NEA2022$pmodel7_empv6_T - NEA2022$predicted_6

summary_preds_6 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_6 = mean(predicted_6, na.rm = TRUE),
    se_pred_6 = sd(residual_6, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_6, aes(x = leeftijd, y = mean_pred_6, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_6 - se_pred_6,
                    ymax = mean_pred_6 + se_pred_6),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability overall unsafety Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```


```{r top/bottom 10 overall unsafety, cache=TRUE}
pred_df_6 <- NEA2022 %>%
  mutate(
    pred_6 = predict(flb_6_1, type = "response", se.fit = TRUE)$fit,
    se_pred_6 = predict(flb_6_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_6 = mean(pred_6, na.rm = TRUE), 
    se_mean_6 = mean(se_pred_6, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_6 <- pred_df_6 %>%
  mutate(
    lower_CI = pred_mean_6 - 1.96 * se_mean_6,
    upper_CI = pred_mean_6 + 1.96 * se_mean_6
  )


list_6 <- pred_df_6 %>%
  arrange(desc(pred_mean_6)) %>%
  mutate(rank = row_number())

top10_6 <- list_6 %>% slice(1:10)
bottom10_6 <- list_6 %>% slice((n() - 9):n())


list_6 <- bind_rows(
  top10_6 %>% mutate(type = "Top 10"),
  bottom10_6 %>% mutate(type = "Bottom 10")
)

print(list_6)

```

<br><br>

# Supervisor unsafety (Class 4)

<br><br>


```{r regression supervisor unsafety, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv4 = pmodel7_empv4)

NEA2022$pmodel7_empv4_T <- (NEA2022$pmodel7_empv4 * (29923 - 1) + 0.5) / 29923

flb_4_0 <- glmmTMB(pmodel7_empv4_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_4_1 <- glmmTMB(pmodel7_empv4_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_4_0)
summary(flb_4_1)
tidy(flb_4_1, effects = "fixed", conf.int = TRUE)
```


```{r Calculation ICC, cache=TRUE}

mu <- fitted(flb_4_0)
var_y <- mu * (1 - mu) / (1 + 3.04)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 0.0002261/(0.0002261+0.01130487), "\n",
    "ICC final: ", 1.918e-09/(1.918e-09+0.01130487), "\n",
    "PCV: ", (0.0002261-1.918e-09)/0.0002261, "\n")
```


```{r Model1: Predicted probability supervisor unsafety, cache=TRUE}
NEA2022$predicted_4 <- predict(flb_4_1, re.form = NULL, type = "response")

NEA2022$residual_4 <- NEA2022$pmodel7_empv4_T - NEA2022$predicted_4

summary_preds_4 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_4 = mean(predicted_4, na.rm = TRUE),
    se_pred_4 = sd(residual_4, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_4, aes(x = leeftijd, y = mean_pred_4, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_4 - se_pred_4,
                    ymax = mean_pred_4 + se_pred_4),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability overall unsafety Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```


```{r top/bottom 10 supervisor unsafety, cache=TRUE}
pred_df_4 <- NEA2022 %>%
  mutate(
    pred_4 = predict(flb_4_1, type = "response", se.fit = TRUE)$fit,
    se_pred_4 = predict(flb_4_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_4 = mean(pred_4, na.rm = TRUE), 
    se_mean_4 = mean(se_pred_4, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_4 <- pred_df_4 %>%
  mutate(
    lower_CI = pred_mean_4 - 1.96 * se_mean_4,
    upper_CI = pred_mean_4 + 1.96 * se_mean_4
  )


list_4 <- pred_df_4 %>%
  arrange(desc(pred_mean_4)) %>%
  mutate(rank = row_number())

top10_4 <- list_4 %>% slice(1:10)
bottom10_4 <- list_4 %>% slice((n() - 9):n())


list_4 <- bind_rows(
  top10_4 %>% mutate(type = "Top 10"),
  bottom10_4 %>% mutate(type = "Bottom 10")
)

print(list_4)

```

<br><br>

# Coworker unsafety (Class 7)

<br><br>

```{r regression coworker unsafety, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv7 = pmodel7_empv7)

NEA2022$pmodel7_empv7_T <- (NEA2022$pmodel7_empv7 * (29923 - 1) + 0.5) / 29923


flb_7_0 <- glmmTMB(pmodel7_empv7_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_7_1 <- glmmTMB(pmodel7_empv7_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_7_0)
summary(flb_7_1)
tidy(flb_7_1, effects = "fixed", conf.int = TRUE)
```


```{r Calculation ICC coworker unsafety, cache=TRUE}

mu <- fitted(flb_7_0)
var_y <- mu * (1 - mu) / (1 + 3.19)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 9.337e-05/(9.337e-05+0.01641693), "\n",
    "ICC final: ", 1.083e-09/(1.083e-09+0.01641763), "\n",
    "PCV: ", (9.337e-05-1.083e-09)/9.337e-05, "\n")
```


```{r Model1: Predicted probability coworker unsafety, cache=TRUE}
NEA2022$predicted_7 <- predict(flb_7_1, re.form = NULL, type = "response")

NEA2022$residual_7 <- NEA2022$pmodel7_empv7_T - NEA2022$predicted_7

summary_preds_7 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_7 = mean(predicted_7, na.rm = TRUE),
    se_pred_7 = sd(residual_7, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_7, aes(x = leeftijd, y = mean_pred_7, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_7 - se_pred_7,
                    ymax = mean_pred_7 + se_pred_7),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability coworker unsafety Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```

```{r top/bottom 10 coworker unsafety, cache=TRUE}
pred_df_7 <- NEA2022 %>%
  mutate(
    pred_7 = predict(flb_7_1, type = "response", se.fit = TRUE)$fit,
    se_pred_7 = predict(flb_7_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_7 = mean(pred_7, na.rm = TRUE), 
    se_mean_7 = mean(se_pred_7, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_7 <- pred_df_7 %>%
  mutate(
    lower_CI = pred_mean_7 - 1.96 * se_mean_7,
    upper_CI = pred_mean_7 + 1.96 * se_mean_7
  )


list_7 <- pred_df_7 %>%
  arrange(desc(pred_mean_7)) %>%
  mutate(rank = row_number())

top10_7 <- list_7 %>% slice(1:10)
bottom10_7 <- list_7 %>% slice((n() - 9):n())


list_7 <- bind_rows(
  top10_7 %>% mutate(type = "Top 10"),
  bottom10_7 %>% mutate(type = "Bottom 10")
)

print(list_7)

```

<br><br>

# Unsafe social climate (Class 5)

<br><br>

```{r regression unsafe social climate, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv5 = pmodel7_empv5)

NEA2022$pmodel7_empv5_T <- (NEA2022$pmodel7_empv5 * (29923 - 1) + 0.5) / 29923

flb_5_0 <- glmmTMB(pmodel7_empv5_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_5_1 <- glmmTMB(pmodel7_empv5_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_5_0)
summary(flb_5_1)
tidy(flb_5_1, effects = "fixed", conf.int = TRUE)
```


```{r Calculation ICC unsafe social climate, cache=TRUE}

mu <- fitted(flb_5_0)
var_y <- mu * (1 - mu) / (1 + 1.35)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 0.002426/(0.002426+0.0547113), "\n",
    "ICC final: ", 3.259e-09/(3.259e-09+0.05471132), "\n",
    "PCV: ", (0.002426 - 3.259e-09)/0.002426, "\n")
```


```{r Model1: Predicted probability unsafe social climate, cache=TRUE}
NEA2022$predicted_5 <- predict(flb_5_0, re.form = NULL, type = "response")

NEA2022$residual_5 <- NEA2022$pmodel7_empv5_T - NEA2022$predicted_5

summary_preds_5 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_5 = mean(predicted_5, na.rm = TRUE),
    se_pred_5 = sd(residual_5, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_5, aes(x = leeftijd, y = mean_pred_5, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_5 - se_pred_5,
                    ymax = mean_pred_5 + se_pred_5),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability unsafe social climate Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```

```{r top/bottom 10 unsafe social climate, cache=TRUE}
pred_df_5 <- NEA2022 %>%
  mutate(
    pred_5 = predict(flb_5_1, type = "response", se.fit = TRUE)$fit,
    se_pred_5 = predict(flb_5_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_5 = mean(pred_5, na.rm = TRUE), 
    se_mean_5 = mean(se_pred_5, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_5 <- pred_df_5 %>%
  mutate(
    lower_CI = pred_mean_5 - 1.96 * se_mean_5,
    upper_CI = pred_mean_5 + 1.96 * se_mean_5
  )


list_5 <- pred_df_5 %>%
  arrange(desc(pred_mean_5)) %>%
  mutate(rank = row_number())

top10_5 <- list_5 %>% slice(1:10)
bottom10_5 <- list_5 %>% slice((n() - 9):n())


list_5 <- bind_rows(
  top10_5 %>% mutate(type = "Top 10"),
  bottom10_5 %>% mutate(type = "Bottom 10")
)

print(list_5)

```

<br><br>

# Short-term conflict (class 1)

<br><br>


```{r short-term conflict, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv1 = pmodel7_empv1)

NEA2022$pmodel7_empv1_T <- (NEA2022$pmodel7_empv1 * (29923 - 1) + 0.5) / 29923

flb_1_0 <- glmmTMB(pmodel7_empv1_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_1_1 <- glmmTMB(pmodel7_empv1_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_1_0)
summary(flb_1_1)
```


```{r Calculation short-term conflict, cache=TRUE}

mu <- fitted(flb_1_0)
var_y <- mu * (1 - mu) / (1 + 1.58)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 0.002186/(0.002186+0.03605616), "\n",
    "ICC final: ", 3.377e-09/(3.377e-09+0.03605616), "\n",
    "PCV: ", (0.002186 - 3.377e-09)/0.002186, "\n")
```


```{r Model1: Predicted probability short-term conflict, cache=TRUE}
NEA2022$predicted_1 <- predict(flb_1_0, re.form = NULL, type = "response")

NEA2022$residual_1 <- NEA2022$pmodel7_empv1_T - NEA2022$predicted_1

summary_preds_1 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_1 = mean(predicted_1, na.rm = TRUE),
    se_pred_1 = sd(residual_1, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_1, aes(x = leeftijd, y = mean_pred_1, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_1 - se_pred_1,
                    ymax = mean_pred_1 + se_pred_1),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability unsafe social climate Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```

```{r top/bottom 10 short-term conflict, cache=TRUE}
pred_df_1 <- NEA2022 %>%
  mutate(
    pred_1 = predict(flb_1_1, type = "response", se.fit = TRUE)$fit,
    se_pred_1 = predict(flb_1_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_1 = mean(pred_1, na.rm = TRUE), 
    se_mean_1 = mean(se_pred_1, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_1 <- pred_df_1 %>%
  mutate(
    lower_CI = pred_mean_1 - 1.96 * se_mean_1,
    upper_CI = pred_mean_1 + 1.96 * se_mean_1
  )


list_1 <- pred_df_1 %>%
  arrange(desc(pred_mean_1)) %>%
  mutate(rank = row_number())

top10_1 <- list_1 %>% slice(1:10)
bottom10_1 <- list_1 %>% slice((n() - 9):n())


list_1 <- bind_rows(
  top10_1 %>% mutate(type = "Top 10"),
  bottom10_1 %>% mutate(type = "Bottom 10")
)

print(list_1)

```

<br><br>

# Safe (Class 2)

<br><br>


```{r regression safe, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv2 = pmodel7_empv2)

NEA2022$pmodel7_empv2_T <- (NEA2022$pmodel7_empv2 * (29923 - 1) + 0.5) / 29923

flb_2_0 <- glmmTMB(pmodel7_empv2_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_2_1 <- glmmTMB(pmodel7_empv2_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_2_0)
summary(flb_2_1)
```


```{r Calculation ICC safe, cache=TRUE}

mu <- fitted(flb_2_0)
var_y <- mu * (1 - mu) / (1 + 0.817)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 0.005225/(0.005225+0.1330826), "\n",
    "ICC final: ", 0.00193/(0.00193+0.1330826), "\n",
    "PCV: ", (0.005225 - 0.00193)/0.005225, "\n")
```


```{r Model1: Predicted probability safe, cache=TRUE}
NEA2022$predicted_2 <- predict(flb_2_0, re.form = NULL, type = "response")

NEA2022$residual_2 <- NEA2022$pmodel7_empv2_T - NEA2022$predicted_2

summary_preds_2 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_2 = mean(predicted_2, na.rm = TRUE),
    se_pred_2 = sd(residual_2, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_2, aes(x = leeftijd, y = mean_pred_2, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_2 - se_pred_2,
                    ymax = mean_pred_2 + se_pred_2),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability unsafe social climate Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```

```{r top/bottom 10 safe, cache=TRUE}
pred_df_2 <- NEA2022 %>%
  mutate(
    pred_2 = predict(flb_2_1, type = "response", se.fit = TRUE)$fit,
    se_pred_2 = predict(flb_2_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_2 = mean(pred_2, na.rm = TRUE), 
    se_mean_2 = mean(se_pred_2, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_2 <- pred_df_2 %>%
  mutate(
    lower_CI = pred_mean_2 - 1.96 * se_mean_2,
    upper_CI = pred_mean_2 + 1.96 * se_mean_2
  )


list_2 <- pred_df_2 %>%
  arrange(desc(pred_mean_2)) %>%
  mutate(rank = row_number())

top10_2 <- list_2 %>% slice(1:10)
bottom10_2 <- list_2 %>% slice((n() - 9):n())


list_2 <- bind_rows(
  top10_2 %>% mutate(type = "Top 10"),
  bottom10_2 %>% mutate(type = "Bottom 10")
)

print(list_2)

```

<br><br>

# Highly safe (Class 3)

<br><br>


```{r regression highly safe, cache=TRUE}
NEA2022 <- NEA2022 %>%
  mutate(pmodel7_empv3 = pmodel7_empv3)

NEA2022$pmodel7_empv3_T <- (NEA2022$pmodel7_empv3 * (29923 - 1) + 0.5) / 29923

flb_3_0 <- glmmTMB(pmodel7_empv3_T ~ 1 + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)

flb_3_1 <- glmmTMB(pmodel7_empv3_T ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd__35.55 + leeftijd__55.75  + (1 | intersections),
                  family = beta_family(link = "logit"),
                  data = NEA2022)
summary(flb_3_0)
summary(flb_3_1)
```


```{r Calculation ICC highly safe, cache=TRUE}

mu <- fitted(flb_3_0)
var_y <- mu * (1 - mu) / (1 + 0.745)
mean_var_within <- mean(var_y)

cat("Residual variance: ", mean(var_y), "\n",
    "ICC model 0: ", 0.01372/(0.01372+0.1169316), "\n",
    "ICC final: ", 0.000689/(0.000689+0.1169316), "\n",
    "PCV: ", (0.01372 - 0.000689)/0.01372, "\n")
```


```{r Model1: Predicted probability highly safe, cache=TRUE}
NEA2022$predicted_3 <- predict(flb_3_0, re.form = NULL, type = "response")

NEA2022$residual_3 <- NEA2022$pmodel7_empv3_T - NEA2022$predicted_3

summary_preds_3 <- NEA2022 %>%
  group_by(gender, migration, education, leeftijd) %>%
  summarise(
    mean_pred_3 = mean(predicted_3, na.rm = TRUE),
    se_pred_3 = sd(residual_3, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  )

gender_labels <- as_labeller(c(
  "m" = "Men",
  "v" = "Women"
))

migration_labels <- as_labeller(c(
  "nl"   = "No migration background",
  "eu"   = "European",
  "noeu" = "Non-European"
))

education_labels <- as_labeller(c(
  "laag"   = "Low",
  "middel" = "Middle",
  "hoog"   = "High"
))

ggplot(summary_preds_3, aes(x = leeftijd, y = mean_pred_3, color = gender)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_pred_3 - se_pred_3,
                    ymax = mean_pred_3 + se_pred_3),
                width = 0,
                alpha = 0.4,
                linewidth = 0.005
                ) + 
  facet_grid(rows = vars(education), cols = vars(migration),
             labeller = labeller(
               education = education_labels,
               migration = migration_labels
             ),
             switch = "y"
  ) +
  labs(
    title = "Predicted probability unsafe social climate Model1",
    y = NULL,
    x = NULL,
    color = "Gender"
  ) +
  scale_color_manual(values = c("m" = "steelblue", "v" = "tomato"),
                     labels = gender_labels) +
  theme_minimal() +
  theme(
    axis.title.y.right = element_text(angle = 90),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0),
    axis.title.y = element_blank(),
    axis.text.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    plot.margin = margin(10, 30, 10, 10)
  ) +
  scale_y_continuous(
    name = NULL,
    sec.axis = dup_axis(name = "Predicted Probability")
  )
```

```{r top/bottom 10 highly safe, cache=TRUE}
pred_df_3 <- NEA2022 %>%
  mutate(
    pred_3 = predict(flb_3_1, type = "response", se.fit = TRUE)$fit,
    se_pred_3 = predict(flb_3_1, type = "response", se.fit = TRUE)$se.fit
  ) %>%
  group_by(intersections) %>%
  summarise(
    pred_mean_3 = mean(pred_3, na.rm = TRUE), 
    se_mean_3 = mean(se_pred_3, na.rm = TRUE)
  ) %>%
  ungroup()

pred_df_3 <- pred_df_3 %>%
  mutate(
    lower_CI = pred_mean_3 - 1.96 * se_mean_3,
    upper_CI = pred_mean_3 + 1.96 * se_mean_3
  )


list_3 <- pred_df_3 %>%
  arrange(desc(pred_mean_3)) %>%
  mutate(rank = row_number())

top10_3 <- list_3 %>% slice(1:10)
bottom10_3 <- list_3 %>% slice((n() - 9):n())


list_3 <- bind_rows(
  top10_3 %>% mutate(type = "Top 10"),
  bottom10_3 %>% mutate(type = "Bottom 10")
)

print(list_3)

```
