---
title: "Class model"
output: html_document
date: "2025-02-27"
---

```{r klippy21, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA2022_clust1 <-read.spss("data/processed/NEA2022_clust1.sav", use.value.labels = T, to.data.frame = T)
attach(NEA2022_clust1)
#NEA20142022 <-read.spss("data/raw/Data 2014-2022.sav", use.value.labels = T, to.data.frame = T)
```

```{r, cache=TRUE}
predclass_5ss <- model5ss$predclass
```

```{r, cache=TRUE}
NEA2022_clust1$class2 <- ifelse(predclass_5ss == 2, 1, 0)  # Create a binary outcome variable
table(NEA2022_clust1$class2)

table(NEA2022_clust1$afl_sb_2, NEA2022_clust1$class2)

library(dplyr)
library(janitor)

table(NEA2022_clust1$afl_sb_2[NEA2022_clust1$class2 == 1])

table(NEA2022_clust1$afl_sb_3[NEA2022_clust1$class2 == 1])
table(NEA2022_clust1$m_v[NEA2022_clust1$class2 == 1])
table(NEA2022_clust1$afl_soi3[NEA2022_clust1$class2 == 1])
table(NEA2022_clust1$vrllandd[NEA2022_clust1$class2 == 1])
table(NEA2022_clust1$afl_lftc[NEA2022_clust1$class2 == 1])




NEA2022_clust1 %>%
  tabyl(class2, afl_sb_2) %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting()


model <- glm(class2 ~ job_sector, data = NEA2022_clust1, family = binomial)
summary(model)
```



