---
title: "Preparing dataset"
output: html_document
date: "2025-05-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library("formatR")
library("foreign")
library("ggplot2")
library("lme4")
library("poLCA")
library("reprex")
library("tidyr")
library("klippy")
library("dplyr")
library("haven")
library("psych")
```
<br><br> **Loading in the data**

```{r loading data, results='hide', warning=FALSE, message=FALSE, echo=TRUE}
NEAraw <-read.spss("data/raw/Data 2014-2022.sav", use.value.labels = T, to.data.frame = T)
```

<br><br> **Selecting year 2022 and cluster 1**

```{r selecting year cluster, echo=TRUE}
NEA2022 <- NEAraw[NEAraw$jaar == "2022", ]

NEA2022 <- NEA2022[NEA2022$se_clust == 1, ]
```

<br><br> **Deleting missing cases on educational level**

```{r missings, echo=TRUE}
NEA2022$afl_soi3[NEA2022$afl_soi3 == "onbekend"] <- NA

NEA2022 <- NEA2022 %>%
  filter(!is.na(afl_soi3))
```

<br><br> **Recoding variables**

```{r bul cow, echo=TRUE}
#Bullying coworkers

NEA2022$pesten_col <- as.numeric(NEA2022$afl_pe_1)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(pesten_col = recode(pesten_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_pe_1)
summarytools::freq(NEA2022$pesten_col)

```

```{r bul sup, echo=TRUE}
#Bullying supervisors
NEA2022$pesten_leid <- as.numeric(NEA2022$afl_pe_2)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(pesten_leid = recode(pesten_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_pe_2)
summarytools::freq(NEA2022$pesten_leid)
```

```{r int cow, echo=TRUE}
#Intimidation coworkers

NEA2022$intimidation_col <- as.numeric(NEA2022$afl_be_1)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(intimidation_col = recode(intimidation_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_be_1)
summarytools::freq(NEA2022$intimidation_col)

```

```{r int sup, echo=TRUE}
#Intimidation supervisors

NEA2022$intimidation_leid <- as.numeric(NEA2022$afl_be_2)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(intimidation_leid = recode(intimidation_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_be_2)
summarytools::freq(NEA2022$intimidation_leid)

```

```{r vio cow, echo=TRUE}
#Physical violence coworkers

NEA2022$geweld_col <- as.numeric(NEA2022$afl_ge_3)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(geweld_col = recode(geweld_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_ge_3)
summarytools::freq(NEA2022$geweld_col)

```

```{r vio sup, echo=TRUE}
#Physical violence supervisors

NEA2022$geweld_leid <- as.numeric(NEA2022$afl_ge_4)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(geweld_leid = recode(geweld_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_ge_4)
summarytools::freq(NEA2022$geweld_leid)
```

```{r sex cow, echo=TRUE}
#Unwanted sexual attention coworkers

NEA2022$seks_col <- as.numeric(NEA2022$afl_se_1)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(seks_col = recode(seks_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_se_1)
summarytools::freq(NEA2022$seks_col)
```

```{r sex sup, echo=TRUE}
#Unwanted sexual attention supervisors
NEA2022$seks_leid <- as.numeric(NEA2022$afl_se_2)

# (1) no, never, (2) a few times, (3) often, and (4) very often 

NEA2022 <- NEA2022 %>%
  mutate(seks_leid = recode(seks_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

summarytools::freq(NEA2022$afl_se_2)
summarytools::freq(NEA2022$seks_leid)

```

```{r con cow, echo=TRUE}
#Conflict coworker

NEA2022$conflict_col <- as.numeric(NEA2022$conflict)

summarytools::freq(NEA2022$conflict)
summarytools::freq(NEA2022$conflict_col)
```

```{r con sup, echo=TRUE}
#Conflict supervisor

NEA2022$conflict_leid <- as.numeric(NEA2022$confli_1)

summarytools::freq(NEA2022$confli_1)
summarytools::freq(NEA2022$conflict_leid)
```

```{r con emp, echo=TRUE}
#Conflict employer

NEA2022$conflict_emp <- as.numeric(NEA2022$confli_2)

summarytools::freq(NEA2022$confli_2)
summarytools::freq(NEA2022$conflict_emp)
```


```{r inc sup, echo=TRUE}
#Social support supervisor: my supervisor pays attention to the well-being of the staff 

NEA2022$leiding_[NEA2022$leiding_ == "nvt"] <- NA

NEA2022$steunleid_welzijn <- as.numeric(NEA2022$leiding_)

#Reverse coding

NEA2022 <- NEA2022 %>%
  mutate(steunleid_welzijn = recode(steunleid_welzijn, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

summarytools::freq(NEA2022$leiding_)
summarytools::freq(NEA2022$steunleid_welzijn)

#Social support supervisor:  my supervisor pays attention to what I say

NEA2022$leidin_1[NEA2022$leidin_1 == "nvt"] <- NA

NEA2022$steunleid_aandacht <- as.numeric(NEA2022$leidin_1)

#Reverse coding

NEA2022 <- NEA2022 %>%
  mutate(steunleid_aandacht = recode(steunleid_aandacht, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

summarytools::freq(NEA2022$leidin_)
summarytools::freq(NEA2022$steunleid_aandacht)

#Cronbach's alpha

steunleid <- data.frame(
  steunleid_aandacht = NEA2022$steunleid_aandacht,
  steunleid_welzijn = NEA2022$steunleid_welzijn
)

alpha_result1 <- alpha(steunleid, use="pairwise.complete.obs")
print(alpha_result1$total$raw_alpha)


#Making a mean scale

NEA2022$steunleid_scale <- rowMeans(NEA2022[c("steunleid_aandacht", "steunleid_welzijn")], na.rm = TRUE)
summarytools::freq(NEA2022$steunleid_scale)


NEA2022$steunleid_R <- as.numeric(factor(NEA2022$steunleid_scale))
NEA2022$steunleid_R[NEA2022$steunleid_R == "8"] <- NA
summarytools::freq(NEA2022$steunleid_R)

#Rounding to a four-point scale
NEA2022 <- NEA2022 %>%
  mutate(steunleid_RR = case_when(
    steunleid_scale %in% c(1) ~ 1,
    steunleid_scale %in% c(1.5, 2) ~ 2,
    steunleid_scale %in% c(2.5, 3) ~ 3,
    steunleid_scale %in% c(3.5, 4) ~ 4,
    TRUE ~ NA_real_
  ))
summarytools::freq(NEA2022$steunleid_RR)

#correlation original and rounded scale
cor(NEA2022$steunleid_scale, NEA2022$steunleid_RR, use = "complete.obs")
```


```{r inc cow, echo=TRUE}
#Social support coworkers: my co-workers take personal interest in me

NEA2022$collega_[NEA2022$collega_ == "nvt"] <- NA

NEA2022$steuncol_belang <- as.numeric(NEA2022$collega_)


#Reverse coding

NEA2022 <- NEA2022 %>%
  mutate(steuncol_belang = recode(steuncol_belang, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

summarytools::freq(NEA2022$collega_)
summarytools::freq(NEA2022$steuncol_belang)

#Social support coworkers: my coworkers are friendly

NEA2022$colleg_1[NEA2022$colleg_1 == "nvt"] <- NA

NEA2022$steuncol_vriendelijk <- as.numeric(NEA2022$colleg_1)

#Reverse coding the scale

NEA2022 <- NEA2022 %>%
  mutate(steuncol_vriendelijk = recode(steuncol_vriendelijk, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

summarytools::freq(NEA2022$colleg_1)
summarytools::freq(NEA2022$steuncol_vriendelijk)

#Cronbach's alpha

steuncol <- data.frame(
  steuncol_belang = NEA2022$steuncol_belang,
  steuncol_vriendelijk = NEA2022$steuncol_vriendelijk
)

alpha_result2 <- alpha(steuncol, use="pairwise.complete.obs")
print(alpha_result2$total$raw_alpha)


#Making a mean scale
NEA2022$steuncol_scale <- rowMeans(NEA2022[c("steuncol_belang", "steuncol_vriendelijk")], na.rm = TRUE)

summarytools::freq(NEA2022$steuncol_scale)

NEA2022$steuncol_R <- as.numeric(factor(NEA2022$steuncol_scale))
NEA2022$steuncol_R[NEA2022$steuncol_R == "8"] <- NA
summarytools::freq(NEA2022$steuncol_R)

#Rounding to a four-point scale
NEA2022 <- NEA2022 %>%
  mutate(steuncol_RR = case_when(
    steuncol_scale %in% c(1) ~ 1,
    steuncol_scale %in% c(1.5, 2) ~ 2,
    steuncol_scale %in% c(2.5, 3) ~ 3,
    steuncol_scale %in% c(3.5, 4) ~ 4,
    TRUE ~ NA_real_
  ))
summarytools::freq(NEA2022$steuncol_RR)

# Correlation original and rounded scale
cor(NEA2022$steuncol_scale, NEA2022$steuncol_RR, use = "complete.obs")
```


```{r psych, echo=TRUE}
#Psychological unsafety: at my workplace it is possible to raise difficult questions

NEA2022$psyveil_last <- as.numeric(NEA2022$psyveil_)
summarytools::freq(NEA2022$psyveil_)
summarytools::freq(NEA2022$psyveil_last)

#Psychological unsafety: at my workplace it is easy to ask for help

NEA2022$psyveil_hulp <- as.numeric(NEA2022$psyvei_1)
summarytools::freq(NEA2022$psyvei_1)
summarytools::freq(NEA2022$psyveil_hulp)

#Psychological unsafety: at my workplace it is okay to make a mistake

NEA2022$psyveil_fout <- as.numeric(NEA2022$psyvei_2)
summarytools::freq(NEA2022$psyvei_2)
summarytools::freq(NEA2022$psyveil_fout)

#Cronbach's alpha

psyveil <- data.frame(
  psyveil_last = NEA2022$psyveil_last,
  psyveil_hulp = NEA2022$psyveil_hulp,
  psyveil_fout = NEA2022$psyveil_fout
)

alpha_result3 <- alpha(psyveil, use="pairwise.complete.obs")
print(alpha_result3$total$raw_alpha)

# Making a mean scale

NEA2022$psyveil_scale <- rowMeans(NEA2022[c("psyveil_last", "psyveil_hulp", "psyveil_fout")], na.rm = TRUE)

summarytools::freq(NEA2022$psyveil_scale)

NEA2022$psyveil_R <- as.numeric(factor(NEA2022$psyveil_scale))

NEA2022$psyveil_R[NEA2022$psyveil_R == "18"] <- NA
summarytools::freq(NEA2022$psyveil_R)

# Rounding to a five-point scale

NEA2022 <- NEA2022 %>%
  mutate(psyveil_RR = case_when(
    psyveil_R %in% c(1, 2) ~ 1,
    psyveil_R %in% c(3, 4, 5, 6) ~ 2,
    psyveil_R %in% c(7, 8, 9, 10) ~ 3,
    psyveil_R %in% c(11, 12, 13, 14) ~ 4,
    psyveil_R %in% c(15, 16, 17) ~ 5,
    TRUE ~ NA_real_
  ))
summarytools::freq(NEA2022$psyveil_RR)

# Correlation original and rounded scale
cor(NEA2022$psyveil_scale, NEA2022$psyveil_RR, use = "complete.obs")
```


<br><br> **Recoden low (15-35), middle (35-55), old (55-75)**

```{r age, echo=TRUE}

NEA2022$lft_num <- as.numeric(NEA2022$afl_lftc)

NEA2022 <- NEA2022 %>%
  mutate(leeftijd = case_when(
    lft_num %in% c(1, 2) ~ 1,
    lft_num %in% c(3, 4) ~ 2,
    lft_num %in% c(5, 6) ~ 3,
    TRUE ~ NA_real_
  ))

NEA2022$leeftijd_ <- factor(NEA2022$leeftijd,
                                 levels = c(1, 2, 3),
                                 labels = c("15.35", "35.55", "55.75"))

summarytools::freq(NEA2022$afl_lftc)
summarytools::freq(NEA2022$leeftijd_)

```

<br><br> **Preparing variables for intersections**

```{r intersections, echo=TRUE}
# Easier labels
NEA2022 <- NEA2022 %>%
  mutate(gender = recode(m_v,
                               "man" = "m",
                               "vrouw" = "v"))

table(NEA2022$vrllandd)
NEA2022 <- NEA2022 %>%
  mutate(migration = recode(vrllandd,
                               "Nederland" = "nl",
                               "Europa (exclusief Nederland)" = "eu",
                               "Buiten Europa" = "noeu"))
table(NEA2022$afl_soi3)
NEA2022 <- NEA2022 %>%
  mutate(education = recode(afl_soi3,
                               "laag opleidingsniveau" = "laag",
                               "middelbaar opleidingsniveau" = "middel",
                               "hoog opleidingsniveau" = "hoog"))

NEA2022$education[NEA2022$education == "onbekend"] <- NA
NEA2022$education[NEA2022$migration == "Onbekend"] <- NA

# Drop unused levels
levels(NEA2022$migration)
NEA2022$migration <- droplevels(NEA2022$migration)
levels(NEA2022$migration)

levels(NEA2022$education)
NEA2022$education <- droplevels(NEA2022$education)
levels(NEA2022$education)

NEA2022$intersections <- interaction(NEA2022$gender, NEA2022$migration, NEA2022$education, NEA2022$leeftijd_)

summarytools::freq(NEA2022$intersections)
```

<br><br> **Creating dummy variables**

```{r dummies, echo=TRUE}
library(fastDummies)
NEA2022 <- dummy_cols(NEA2022, select_columns = "gender", remove_first_dummy = FALSE)
NEA2022 <- dummy_cols(NEA2022, select_columns = "migration", remove_first_dummy = FALSE)
NEA2022 <- dummy_cols(NEA2022, select_columns = "education", remove_first_dummy = FALSE)
NEA2022 <- dummy_cols(NEA2022, select_columns = "leeftijd_", remove_first_dummy = FALSE)
NEA2022 <- dummy_cols(NEA2022, select_columns = "intersections", remove_first_dummy = FALSE)

dummy_columns <- grep("^intersections_", colnames(NEA2022), value = TRUE)
colnames(NEA2022)[colnames(NEA2022) %in% dummy_columns] <- gsub("^intersections_", "", dummy_columns)
```

