---
title: "Factoranalyse"
output: html_document
date: "2025-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy6, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r}
library("formatR")
library("foreign")
library("ggplot2")
library("lme4")
library("poLCA")
library("reprex")
library("tidyr")
library("klippy")
library("dplyr")
library("haven")
library("psych")
library("GPArotation")
library("Hmisc")

```

```{r klippy7, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal <-read.spss("data/processed/NEAfinal.sav", use.value.labels = T, to.data.frame = T)
attach(NEAfinal)
```

```{r}
datafactor <- data.frame(pesten_col, pesten_leid, intimidation_col, intimidation_leid, geweld_col, geweld_leid, seks_col, seks_leid)
```

```{r}
cor_matrix <- cor(datafactor, use = "pairwise.complete.obs")
print(cor_matrix)
```

```{r}
kable(round(cor_matrix, 3))
```

```{r}
library(Hmisc)
cor_results <- rcorr(as.matrix(datafactor))

cor_matrix <- round(cor_results$r, 3)
p_matrix <- cor_results$P

cor_with_stars <- function(cor_matrix, p_matrix) {
  stars <- ifelse(is.na(p_matrix), "",
           ifelse(p_matrix < 0.001, "***",
           ifelse(p_matrix < 0.01, "**",
           ifelse(p_matrix < 0.05, "*", ""))))
  
  cor_matrix_formatted <- matrix(
    paste0(format(cor_matrix, nsmall = 3), stars),
    nrow = nrow(cor_matrix), 
    dimnames = dimnames(cor_matrix)
  )
  
  return(cor_matrix_formatted)
}

cor_matrix_stars <- cor_with_stars(cor_matrix, p_matrix)

kable(cor_matrix_stars)

```

```{r}
fa.parallel(datafactor, fa = "fa", n.iter = 100, show.legend = FALSE)
```

```{r}
efa <- fa(datafactor, nfactors = 4, rotate = "oblimin", fm = "ml")
print(efa, digits = 2)
```


```{r}
psyveil <- data.frame(psyveil_last, psyveil_hulp, psyveil_fout)

alpha_result <- alpha(psyveil)

print(alpha_result)
```

```{r}
steuncol <- data.frame(steuncol_belang, steuncol_vriendelijk)

alpha_result2 <- alpha(steuncol)

print(alpha_result2)
```

```{r}
steunleid <- data.frame(steunleid_aandacht, steunleid_welzijn)

alpha_result3 <- alpha(steunleid)

print(alpha_result3)
```


Schaal


```{r}
cor_matrixs <- cor(datafactorschaal, use = "pairwise.complete.obs")
print(cor_matrixs)
```

```{r}
kable(round(cor_matrixs, 3))
```

```{r}
library(Hmisc)
cor_resultss <- rcorr(as.matrix(datafactorschaal))

cor_matrixs <- round(cor_resultss$r, 3)
p_matrixs <- cor_resultss$P

cors_with_stars <- function(cor_matrixs, p_matrixs) {
  starss <- ifelse(is.na(p_matrixs), "",
           ifelse(p_matrixs < 0.001, "***",
           ifelse(p_matrixs < 0.01, "**",
           ifelse(p_matrixs < 0.05, "*", ""))))
  
  cor_matrixs_formatted <- matrix(
    paste0(format(cor_matrixs, nsmall = 3), starss),
    nrow = nrow(cor_matrixs), 
    dimnames = dimnames(cor_matrixs)
  )
  
  return(cor_matrixs_formatted)
}

cor_matrixs_stars <- cors_with_stars(cor_matrixs, p_matrixs)

kable(cor_matrixs_stars)

```

```{r}
fa.parallel(datafactorschaal, fa = "fa", n.iter = 100, show.legend = FALSE)
```

```{r}
efa <- fa(datafactorschaal, nfactors = 6, rotate = "oblimin", fm = "ml")
print(efa, digits = 2)
```

