---
title: "Loading in the data"
#bibliography: references.bib
author: "Nina Branten"
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

----
  
Loading in the necessary packages.
  
```{r}
library("foreign")
library("ggplot2")


```
----
Starting out with loading in the NEA data 2005-2021

```{r}
NEAoud <-read.spss("data/raw/DANS_NEA2005-2018.sav", use.value.labels = T, to.data.frame = T)

```
```{r}
summary(NEAoud$OngwGedr_a)
NEAoud$OngwGedr_a <- as.numeric(NEAoud$OngwGedr_a) 
ggplot(data=NEAoud, aes(x=OngwGedr_a)) + geom_bar(stat="bin")
class(NEAoud$OngwGedr_a)

ggplot(data=NEAoud[!NEAoud$OngwGedr_a==1,], aes(x=OngwGedr_a)) + geom_bar(stat="bin")

```
