

```{r}
NEAfinal$steunleid_scale <- rowMeans(NEAfinal[c("steunleid_aandacht", "steunleid_welzijn")], na.rm = TRUE)
summarytools::freq(NEAfinal$steunleid_scale)
summarytools::freq(NEAfinal$afl_socs)

NEAfinal <- NEAfinal %>%
  mutate(steunleid_RR = case_when(
    steunleid_scale %in% c(1) ~ 1,
    steunleid_scale %in% c(1.5, 2) ~ 2,
    steunleid_scale %in% c(2.5, 3) ~ 3,
    steunleid_scale %in% c(3.5, 4) ~ 4,
    TRUE ~ NA_real_
  ))

summarytools::freq(NEAfinal$steunleid_RR)

NEAfinal <- NEAfinal %>%
  mutate(steunleid_plot3 = (steunleid_RR - 1) / 3)

summarytools::freq(NEAfinal$steunleid_plot3)

```

```{r}
NEAfinal$steuncol_scale <- rowMeans(NEAfinal[c("steuncol_belang", "steuncol_vriendelijk")], na.rm = TRUE)
summarytools::freq(NEAfinal$steuncol_scale)
summarytools::freq(NEAfinal$afl_so_2)

NEAfinal <- NEAfinal %>%
  mutate(steuncol_RR = case_when(
    steuncol_scale %in% c(1) ~ 1,
    steuncol_scale %in% c(1.5, 2) ~ 2,
    steuncol_scale %in% c(2.5, 3) ~ 3,
    steuncol_scale %in% c(3.5, 4) ~ 4,
    TRUE ~ NA_real_
  ))

summarytools::freq(NEAfinal$steuncol_RR)

NEAfinal <- NEAfinal %>%
  mutate(steuncol_plot3 = (steuncol_RR - 1) / 3)

summarytools::freq(NEAfinal$steuncol_plot3)
```

```{r}
NEAfinal$psyveil_scale <- rowMeans(NEAfinal[c("psyveil_last", "psyveil_hulp", "psyveil_fout")], na.rm = TRUE)

summarytools::freq(NEAfinal$psyveil_scale)

NEAfinal$psyveil_R <- as.numeric(factor(NEAfinal$psyveil_scale))

summarytools::freq(NEAfinal$psyveil_R)

NEAfinal$psyveil_R[NEAfinal$psyveil_R == "18"] <- NA


summarytools::freq(NEAfinal$psyveil_scale)
summarytools::freq(NEAfinal$psyveil_R)

NEAfinal <- NEAfinal %>%
  mutate(psyveil_RR = case_when(
    psyveil_R %in% c(1, 2) ~ 1,
    psyveil_R %in% c(3, 4, 5, 6) ~ 2,
    psyveil_R %in% c(7, 8, 9, 10) ~ 3,
    psyveil_R %in% c(11, 12, 13, 14) ~ 4,
    psyveil_R %in% c(15, 16, 17) ~ 5,
    TRUE ~ NA_real_
  ))
summarytools::freq(NEAfinal$psyveil_scale)
summarytools::freq(NEAfinal$psyveil_RR)

NEAfinal <- NEAfinal %>%
  mutate(psyveil_plot3 = (psyveil_RR - 1) / 4)

summarytools::freq(NEAfinal$psyveil_plot3)

```


```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
attach(NEAfinal)
```


```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class2_d <- model2_d$predclass
table(NEAfinal$class2_d)
```
```{r echo=FALSE, message=FALSE, warning=FALSE, include=TRUE, results='hide'}
NEAfinal$class3_d <- model3_d$predclass
table(NEAfinal$class3_d)
```
```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class4_d <- model4_d$predclass
table(NEAfinal$class4_d)
```
```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class5_d <- model5_d$predclass
table(NEAfinal$class5_d)
```
```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class6_d <- model6_d$predclass
table(NEAfinal$class6_d)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class7_d <- model7_d$predclass
table(NEAfinal$class7_d)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class8_d <- model8_d$predclass
table(NEAfinal$class8_d)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class9_d <- model9_d$predclass
table(NEAfinal$class9_d)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEAfinal$class10_d <- model10_d$predclass
table(NEAfinal$class10_d)
```


```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class2_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class2_d, mean, na.rm = TRUE)
```


Class 3

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class3_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class3_d, mean, na.rm = TRUE)
```

Class 4

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class4_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class4_d, mean, na.rm = TRUE)
```

Class 5

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class5_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class5_d, mean, na.rm = TRUE)
```

Class 6

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class6_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class6_d, mean, na.rm = TRUE)
```

Class 7

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class7_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class7_d, mean, na.rm = TRUE)
```

Class 8

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class8_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class8_d, mean, na.rm = TRUE)
```

Class 9

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```
```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```


```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class9_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class9_d, mean, na.rm = TRUE)
```

Class 10

```{r}
tapply(NEAfinal$pesten_col_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$pesten_leid_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_col_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$int_leid_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_col_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$gew_leid_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_col_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$seks_leid_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_col_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_leid_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$conflict_werk_plot, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steunleid_plot3, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$steuncol_plot3, NEAfinal$class10_d, mean, na.rm = TRUE)
```

```{r}
tapply(NEAfinal$psyveil_plot3, NEAfinal$class10_d, mean, na.rm = TRUE)
```

