---
title: "Intersectionality"
#bibliography: references.bib
author: "Nina Branten"
---
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()
 


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy3, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r echo=FALSE, warning=FALSE}
library("foreign")
library("ggplot2")
library("summarytools")
library("dplyr")
library("labelled")
library("tidyr")
library("fastDummies")
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA2022_clust1 <-read.spss("data/processed/NEA2022_clust1.sav", use.value.labels = T, to.data.frame = T)

#NEA20142022 <-read.spss("data/raw/Data 2014-2022.sav", use.value.labels = T, to.data.frame = T)
```


```{r}
NEA2022_clust1$afl_soi3[NEA2022_clust1$afl_soi3 == "onbekend"] <- NA

NEA2022_clust1_29923 <- NEA2022_clust1 %>%
  filter(!is.na(afl_soi3))

attach(NEA2022_clust1_29923)

```

<br><br> **Gender**

```{r}
summarytools::freq(NEA2022_clust1_29923$m_v)
summary(NEA2022_clust1_29923$m_v)
```
<br><br> **Migration background**
```{r}
summarytools::freq(NEA2022_clust1_29923$vrllandd)
```
<br><br> **Educational level**
```{r}
summarytools::freq(NEA2022_clust1_29923$afl_soi3)
```

<br><br> **Age**

```{r}
summarytools::freq(NEA2022_clust1_29923$afl_lftc)
```
<br><br> **Recoden laag (15-35), middelbaar (35-55), hoog (55-75)**

```{r}
summarytools::freq(NEA2022_clust1_29923$afl_lftc)
str(NEA2022_clust1_29923$afl_lftc)


NEA2022_clust1_29923$lft_num <- as.numeric(NEA2022_clust1_29923$afl_lftc)

NEA2022_clust1_29923 <- NEA2022_clust1_29923 %>%
  mutate(leeftijd = case_when(
    lft_num %in% c(1, 2) ~ 1,
    lft_num %in% c(3, 4) ~ 2,
    lft_num %in% c(5, 6) ~ 3,
    TRUE ~ NA_real_
  ))


NEA2022_clust1_29923$leeftijd_ <- factor(NEA2022_clust1_29923$leeftijd,
                                 levels = c(1, 2, 3),
                                 labels = c("15.35", "35.55", "55.75"))


summarytools::freq(NEA2022_clust1_29923$leeftijd_)

```
<br><br> **Preparing variables for intersections**

```{r}
# Easier labels
NEA2022_clust1_29923 <- NEA2022_clust1_29923 %>%
  mutate(gender = recode(m_v,
                               "man" = "m",
                               "vrouw" = "v"))


NEA2022_clust1_29923 <- NEA2022_clust1_29923 %>%
  mutate(migration = recode(vrllandd,
                               "Nederland" = "nl",
                               "Europa (exclusief Nederland)" = "eu",
                               "Buiten Europa" = "noeu"))

NEA2022_clust1_29923 <- NEA2022_clust1_29923 %>%
  mutate(education = recode(afl_soi3,
                               "laag opleidingsniveau" = "laag",
                               "middelbaar opleidingsniveau" = "middel",
                               "hoog opleidingsniveau" = "hoog"))

# Missing values
NEA2022_clust1_29923$education[NEA2022_clust1_29923$education == "onbekend"] <- NA
NEA2022_clust1_29923$education[NEA2022_clust1_29923$migration == "Onbekend"] <- NA

# Drop unused levels
levels(NEA2022_clust1_29923$migration)
NEA2022_clust1_29923$migration <- droplevels(NEA2022_clust1_29923$migration)
levels(NEA2022_clust1_29923$migration)

levels(NEA2022_clust1_29923$education)
NEA2022_clust1_29923$education <- droplevels(NEA2022_clust1_29923$education)
levels(NEA2022_clust1_29923$education)

summary(NEA2022_clust1_29923$gender)
summary(NEA2022_clust1_29923$migration)
summary(NEA2022_clust1_29923$education)
summary(NEA2022_clust1_29923$leeftijd_)

```

```{r}
NEA2022_clust1_29923$intersections <- interaction(NEA2022_clust1_29923$gender, NEA2022_clust1_29923$migration, NEA2022_clust1_29923$education, NEA2022_clust1_29923$leeftijd_)

summarytools::freq(NEA2022_clust1_29923$intersections)


#NEA2022$intersections <- interaction(NEA2022$m_v, NEA2022$vrllandd, NEA2022$afl_soi3, NEA2022$leeftijd_)
#table(NEA2022$intersections) 

#NEA2022$gender_num <- as.numeric(NEA2022$m_v)
#NEA2022$migr_num <- as.numeric(NEA2022$vrllandd)
#NEA2022$educ_num <- as.numeric(NEA2022$afl_soi3)

#NEA2022$intersections_num <- interaction(NEA2022$gender_num, NEA2022$migr_num, NEA2022$educ_num, NEA2022$leeftijd)
#table(NEA2022$intersections_num)
#summary(NEA2022$intersections_num)

```

<br><br> **Creating dummy variables**

```{r}
NEA2022_clust1_29923 <- dummy_cols(NEA2022_clust1_29923, select_columns = "gender", remove_first_dummy = FALSE)
table(NEA2022_clust1_29923$gender_m)
```
```{r}
NEA2022_clust1_29923 <- dummy_cols(NEA2022_clust1_29923, select_columns = "migration", remove_first_dummy = FALSE)
table(NEA2022_clust1_29923$migration_nl)
```
```{r}
NEA2022_clust1_29923 <- dummy_cols(NEA2022_clust1_29923, select_columns = "education", remove_first_dummy = FALSE)
table(NEA2022_clust1_29923$education_laag)
```
```{r}
NEA2022_clust1_29923 <- dummy_cols(NEA2022_clust1_29923, select_columns = "leeftijd_", remove_first_dummy = FALSE)
table(NEA2022_clust1_29923$leeftijd__55.75)
```

```{r}
NEA2022_clust1_29923 <- dummy_cols(NEA2022_clust1_29923, select_columns = "intersections", remove_first_dummy = FALSE)

dummy_columns <- grep("^intersections_", colnames(NEA2022_clust1_29923), value = TRUE)  # Find dummy columns
colnames(NEA2022_clust1_29923)[colnames(NEA2022_clust1_29923) %in% dummy_columns] <- gsub("^intersections_", "", dummy_columns)

table(NEA2022_clust1_29923$v.noeu.hoog.35.55)
table(NEA2022_clust1_29923$m.nl.hoog.35.55)
str(NEA2022_clust1_29923$m.nl.hoog.35.55)
```
```{r}
write.csv(NEA2022_clust1_29923, "data/processed/NEA2022_clust1_29923.sav")
```

