---
title: "LCA binair"
output: html_document
date: "2025-06-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

```{r loading packages, warning=FALSE, results='hide', message=FALSE}
library("formatR")
library("foreign")
library("ggplot2")
library("lme4")
library("poLCA")
library("reprex")
library("tidyr")
library("klippy")
library("dplyr")
library("haven")
library("psych")
```


<br><br> **Loading the data**

```{r loading data, cache=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA2022 <- readRDS("data/processed/NEA1009.rds")

attach(NEA2022)
set.seed(123)
```

<br><br> **Recoding into binary variables**

```{r recoding binary, cache=TRUE}
table(NEA2022$pesten_col)

NEA2022 <- NEA2022 %>%
  mutate(bul_c = case_when(
    pesten_col == 1 ~ 1,
    pesten_col %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$bul_c)


table(NEA2022$pesten_leid)

NEA2022 <- NEA2022 %>%
  mutate(bul_s = case_when(
    pesten_leid == 1 ~ 1,
    pesten_leid %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$bul_s)

table(NEA2022$intimidation_col)

NEA2022 <- NEA2022 %>%
  mutate(int_c = case_when(
    intimidation_col == 1 ~ 1,
    intimidation_col %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$int_c)

table(NEA2022$intimidation_leid)

NEA2022 <- NEA2022 %>%
  mutate(int_s = case_when(
    intimidation_leid == 1 ~ 1,
    intimidation_leid %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$int_s)

table(NEA2022$seks_col)

NEA2022 <- NEA2022 %>%
  mutate(sex_c = case_when(
    seks_col == 1 ~ 1,
    seks_col %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$sex_c)

table(NEA2022$seks_leid)

NEA2022 <- NEA2022 %>%
  mutate(sex_s = case_when(
    seks_leid == 1 ~ 1,
    seks_leid %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$sex_s)

table(NEA2022$geweld_col)

NEA2022 <- NEA2022 %>%
  mutate(vio_c = case_when(
    geweld_col == 1 ~ 1,
    geweld_col %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$vio_c)

table(NEA2022$geweld_leid)

NEA2022 <- NEA2022 %>%
  mutate(vio_s = case_when(
    geweld_leid == 1 ~ 1,
    geweld_leid %in% c(2, 3, 4) ~ 2,
    TRUE ~ NA_real_ 
  ))

table(NEA2022$vio_s)
```

# Latent class analysis

```{r data items, cache=TRUE, warning=FALSE}
attach(NEA2022)
data_b <- data.frame(bul_c, bul_s, int_c, int_s, vio_c, vio_s, sex_c, sex_s, conflict_col, conflict_leid, steunleid_RR, steuncol_RR, psyveil_RR)

items_b <- cbind(bul_c, bul_s, int_c, int_s, vio_c, vio_s, sex_c, sex_s, conflict_col, conflict_leid, steunleid_RR, steuncol_RR, psyveil_RR) ~ 1
```

## Model1
```{r model 1, cache=TRUE}
model1_b <- poLCA(items_b, data_b, nclass = 1, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model2

```{r model 2, cache=TRUE}
model2_b <- poLCA(items_b, data_b, nclass = 2, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model3

```{r model 3, cache=TRUE}
model3_b <- poLCA(items_b, data_b, nclass = 3, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model4

```{r model 4, cache=TRUE}
model4_b <- poLCA(items_b, data_b, nclass = 4, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model5

```{r model 5, cache=TRUE}
model5_b <- poLCA(items_b, data_b, nclass = 5, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model6

```{r model 6, cache=TRUE}
model6_b <- poLCA(items_b, data_b, nclass = 6, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model7

```{r model 7, cache=TRUE}
model7_b <- poLCA(items_b, data_b, nclass = 7, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model8

```{r model 8, cache=TRUE}
model8_b <- poLCA(items_b, data_b, nclass = 8, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model9

```{r model 9, cache=TRUE}
model9_b <- poLCA(items_b, data_b, nclass = 9, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model10

```{r model 10, cache=TRUE}
model10_b <- poLCA(items_b, data_b, nclass = 10, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model11

```{r model 11, cache=TRUE}
model11_b <- poLCA(items_b, data_b, nclass = 11, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```

## Model12

```{r model 12, cache=TRUE}
model12_b <- poLCA(items_b, data_b, nclass = 12, maxiter = 5000, nrep = 10, graphs=FALSE, na.rm = FALSE)
```


# Saving the models

```{r saving models, cache=TRUE}
model3_bpred <- model3_b$predclass
model3_bpost <- model3_b$posterior

lposteriorsmodel3_b <- as.list(as.data.frame(model3_bpost))

pmodel3_bv1 <- lposteriorsmodel3_b[[1]]
pmodel3_bv2 <- lposteriorsmodel3_b[[2]]
pmodel3_bv3 <- lposteriorsmodel3_b[[3]]

model4_bpred <- model4_b$predclass
model4_bpost <- model4_b$posterior

lposteriorsmodel4_b <- as.list(as.data.frame(model4_bpost))

pmodel4_bv1 <- lposteriorsmodel4_b[[1]]
pmodel4_bv2 <- lposteriorsmodel4_b[[2]]
pmodel4_bv3 <- lposteriorsmodel4_b[[3]]
pmodel4_bv4 <- lposteriorsmodel4_b[[4]]


model5_bpred <- model5_b$predclass
model5_bpost <- model5_b$posterior

lposteriorsmodel5_b <- as.list(as.data.frame(model5_bpost))

pmodel5_bv1 <- lposteriorsmodel5_b[[1]]
pmodel5_bv2 <- lposteriorsmodel5_b[[2]]
pmodel5_bv3 <- lposteriorsmodel5_b[[3]]
pmodel5_bv4 <- lposteriorsmodel5_b[[4]]
pmodel5_bv5 <- lposteriorsmodel5_b[[5]]

model6_bpred <- model6_b$predclass
model6_bpost <- model6_b$posterior

lposteriorsmodel6_b <- as.list(as.data.frame(model6_bpost))

pmodel6_bv1 <- lposteriorsmodel6_b[[1]]
pmodel6_bv2 <- lposteriorsmodel6_b[[2]]
pmodel6_bv3 <- lposteriorsmodel6_b[[3]]
pmodel6_bv4 <- lposteriorsmodel6_b[[4]]
pmodel6_bv5 <- lposteriorsmodel6_b[[5]]
pmodel6_bv6 <- lposteriorsmodel6_b[[6]]

model7_bpred <- model7_b$predclass
model7_bpost <- model7_b$posterior

lposteriorsmodel7_b <- as.list(as.data.frame(model7_bpost))

pmodel7_bv1 <- lposteriorsmodel7_b[[1]]
pmodel7_bv2 <- lposteriorsmodel7_b[[2]]
pmodel7_bv3 <- lposteriorsmodel7_b[[3]]
pmodel7_bv4 <- lposteriorsmodel7_b[[4]]
pmodel7_bv5 <- lposteriorsmodel7_b[[5]]
pmodel7_bv6 <- lposteriorsmodel7_b[[6]]
pmodel7_bv7 <- lposteriorsmodel7_b[[7]]

model8_bpred <- model8_b$predclass
model8_bpost <- model8_b$posterior

lposteriorsmodel8_b <- as.list(as.data.frame(model8_bpost))

pmodel8_bv1 <- lposteriorsmodel8_b[[1]]
pmodel8_bv2 <- lposteriorsmodel8_b[[2]]
pmodel8_bv3 <- lposteriorsmodel8_b[[3]]
pmodel8_bv4 <- lposteriorsmodel8_b[[4]]
pmodel8_bv5 <- lposteriorsmodel8_b[[5]]
pmodel8_bv6 <- lposteriorsmodel8_b[[6]]
pmodel8_bv7 <- lposteriorsmodel8_b[[7]]
pmodel8_bv8 <- lposteriorsmodel8_b[[8]]

model9_bpred <- model9_b$predclass
model9_bpost <- model9_b$posterior

lposteriorsmodel9_b <- as.list(as.data.frame(model9_bpost))

pmodel9_bv1 <- lposteriorsmodel9_b[[1]]
pmodel9_bv2 <- lposteriorsmodel9_b[[2]]
pmodel9_bv3 <- lposteriorsmodel9_b[[3]]
pmodel9_bv4 <- lposteriorsmodel9_b[[4]]
pmodel9_bv5 <- lposteriorsmodel9_b[[5]]
pmodel9_bv6 <- lposteriorsmodel9_b[[6]]
pmodel9_bv7 <- lposteriorsmodel9_b[[7]]
pmodel9_bv8 <- lposteriorsmodel9_b[[8]]
pmodel9_bv9 <- lposteriorsmodel9_b[[9]]

model10_bpred <- model10_b$predclass
model10_bpost <- model10_b$posterior

lposteriorsmodel10_b <- as.list(as.data.frame(model10_bpost))

pmodel10_bv1 <- lposteriorsmodel10_b[[1]]
pmodel10_bv2 <- lposteriorsmodel10_b[[2]]
pmodel10_bv3 <- lposteriorsmodel10_b[[3]]
pmodel10_bv4 <- lposteriorsmodel10_b[[4]]
pmodel10_bv5 <- lposteriorsmodel10_b[[5]]
pmodel10_bv6 <- lposteriorsmodel10_b[[6]]
pmodel10_bv7 <- lposteriorsmodel10_b[[7]]
pmodel10_bv8 <- lposteriorsmodel10_b[[8]]
pmodel10_bv9 <- lposteriorsmodel10_b[[9]]
pmodel10_bv10 <- lposteriorsmodel10_b[[10]]

model11_bpred <- model11_b$predclass
model11_bpost <- model11_b$posterior

lposteriorsmodel11_b <- as.list(as.data.frame(model11_bpost))

pmodel11_bv1 <- lposteriorsmodel11_b[[1]]
pmodel11_bv2 <- lposteriorsmodel11_b[[2]]
pmodel11_bv3 <- lposteriorsmodel11_b[[3]]
pmodel11_bv4 <- lposteriorsmodel11_b[[4]]
pmodel11_bv5 <- lposteriorsmodel11_b[[5]]
pmodel11_bv6 <- lposteriorsmodel11_b[[6]]
pmodel11_bv7 <- lposteriorsmodel11_b[[7]]
pmodel11_bv8 <- lposteriorsmodel11_b[[8]]
pmodel11_bv9 <- lposteriorsmodel11_b[[9]]
pmodel11_bv10 <- lposteriorsmodel11_b[[10]]
pmodel11_bv11 <- lposteriorsmodel11_b[[11]]

model12_bpred <- model12_b$predclass
model12_bpost <- model12_b$posterior

lposteriorsmodel12_b <- as.list(as.data.frame(model12_bpost))

pmodel12_bv1 <- lposteriorsmodel12_b[[1]]
pmodel12_bv2 <- lposteriorsmodel12_b[[2]]
pmodel12_bv3 <- lposteriorsmodel12_b[[3]]
pmodel12_bv4 <- lposteriorsmodel12_b[[4]]
pmodel12_bv5 <- lposteriorsmodel12_b[[5]]
pmodel12_bv6 <- lposteriorsmodel12_b[[6]]
pmodel12_bv7 <- lposteriorsmodel12_b[[7]]
pmodel12_bv8 <- lposteriorsmodel12_b[[8]]
pmodel12_bv9 <- lposteriorsmodel12_b[[9]]
pmodel12_bv10 <- lposteriorsmodel12_b[[10]]
pmodel12_bv11 <- lposteriorsmodel12_b[[11]]
pmodel12_bv12 <- lposteriorsmodel12_b[[12]]
```

```{r saving models 2, cache=TRUE}
Models_b <- cbind (volgnumm, model3_bpred	,
                 pmodel3_bv1	,
                 pmodel3_bv2	,
                 pmodel3_bv3	,
                 model4_bpred	,
                 pmodel4_bv1	,
                 pmodel4_bv2	,
                 pmodel4_bv3	,
                 pmodel4_bv4	,
                 model5_bpred	,
                 pmodel5_bv1	,
                 pmodel5_bv2	,
                 pmodel5_bv3	,
                 pmodel5_bv4	,
                 pmodel5_bv5	,
                 model6_bpred	,
                 pmodel6_bv1	,
                 pmodel6_bv2	,
                 pmodel6_bv3	,
                 pmodel6_bv4	,
                 pmodel6_bv5	,
                 pmodel6_bv6	,
                 model7_bpred	,
                 pmodel7_bv1	,
                 pmodel7_bv2	,
                 pmodel7_bv3	,
                 pmodel7_bv4	,
                 pmodel7_bv5	,
                 pmodel7_bv6	,
                 pmodel7_bv7	,
                 model8_bpred	,
                 pmodel8_bv1	,
                 pmodel8_bv2	,
                 pmodel8_bv3	,
                 pmodel8_bv4	,
                 pmodel8_bv5	,
                 pmodel8_bv6	,
                 pmodel8_bv7	,
                 pmodel8_bv8  ,
                 model9_bpred	,
                 pmodel9_bv1	,
                 pmodel9_bv2	,
                 pmodel9_bv3	,
                 pmodel9_bv4	,
                 pmodel9_bv5	,
                 pmodel9_bv6	,
                 pmodel9_bv7	,
                 pmodel9_bv8	,
                 pmodel9_bv9 ,
                 model10_bpred	,
                 pmodel10_bv1 ,
                 pmodel10_bv2 ,
                 pmodel10_bv3 ,
                 pmodel10_bv4 ,
                 pmodel10_bv5 ,
                 pmodel10_bv6 ,
                 pmodel10_bv7 ,
                 pmodel10_bv8 ,
                 pmodel10_bv9 ,
                 pmodel10_bv10 ,
                 model11_bpred	,
                 pmodel11_bv1 ,
                 pmodel11_bv2 ,
                 pmodel11_bv3 ,
                 pmodel11_bv4 ,
                 pmodel11_bv5 ,
                 pmodel11_bv6 ,
                 pmodel11_bv7 ,
                 pmodel11_bv8 ,
                 pmodel11_bv9 ,
                 pmodel11_bv10 ,
                 pmodel11_bv11 ,
                 model12_bpred	,
                 pmodel12_bv1 ,
                 pmodel12_bv2 ,
                 pmodel12_bv3 ,
                 pmodel12_bv4 ,
                 pmodel12_bv5 ,
                 pmodel12_bv6 ,
                 pmodel12_bv7 ,
                 pmodel12_bv8 ,
                 pmodel12_bv9 ,
                 pmodel12_bv10 ,
                 pmodel12_bv11 ,
                 pmodel12_bv12 )
```


```{r}
models_b <- list(
  model3_b, model4_b, model5_b, model6_b, model7_b,
  model8_b, model9_b, model10_b, model11_b, model12_b
)

model_nums_b <- 3:12

Models_b <- data.frame(volgnumm = volgnumm)

for (i in seq_along(models_b)) {
  
  m <- models_b[[i]]
  num <- model_nums_b[i]
  
  Models_b[[paste0("model", num, "_bpred")]] <- m$predclass
  
  post <- as.data.frame(m$posterior)
  names(post) <- paste0("pmodel", num, "_bv", 1:ncol(post))
  
  Models_b <- cbind(Models_b, post)
}

```

```{r}
NEA2022 <- merge(NEA2022, Models_b, by = "volgnumm", all.x = TRUE)
```


# Class separation


```{r post prob, cache=TRUE}
max_probs <- apply(model7_bpost, 1, max)

mean(max_probs)
median(max_probs)
min(max_probs)
max(max_probs)

K <- 7

mean_posteriors <- numeric(K)

for (k in 1:K) {
  idx <- which(model7_bpred == k)
  mean_posteriors[k] <- mean(model7_bpost[idx, k])
}

names(mean_posteriors) <- paste0("Class", 1:K)

mean_posteriors


ggplot(data.frame(max_probs = max_probs), aes(x = max_probs)) +
  geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") +
  geom_vline(aes(xintercept = mean(max_probs)), 
             color = "red", linetype = "dashed", linewidth = 1) +
  labs(title = "Distribution of maximum posterior probabilities",
       x = "Maximum posterior probability",
       y = "Number of respondents") +
  theme_minimal()
```

```{r entropy, cache=TRUE}
poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model2_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model3_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model4_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model5_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model6_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model7_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model8_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model9_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model10_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model11_b)

poLCA.entropy <- function(model) {
  P <- model$posterior
  entropy <- sum(-P * log(P), na.rm=TRUE) / (nrow(P) * log(ncol(P)))
  return(1 - entropy)
}
poLCA.entropy(model12_b)
```



# Plots

```{r rocoding plot, echo=TRUE}
#Recoding variables on scale from 0 to 1

NEA2022 <- NEA2022 %>%
  mutate(bul_c_plot = recode(bul_c, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(bul_s_plot = recode(bul_s, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(int_c_plot = recode(int_c, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(int_s_plot = recode(int_s, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(vio_c_plot = recode(vio_c, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(vio_s_plot = recode(vio_s, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(sex_c_plot = recode(sex_c, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(sex_s_plot = recode(sex_s, `1` = 0, `2` = 1))

NEA2022 <- NEA2022 %>%
  mutate(conflict_col_plot = recode(conflict_col, `1` = 0, `2` = 0.50, `3` = 1))

NEA2022 <- NEA2022 %>%
  mutate(conflict_leid_plot = recode(conflict_leid, `1` = 0, `2` = 0.50, `3` = 1))

NEA2022 <- NEA2022 %>%
  mutate(steunleid_plot = (steunleid_RR - 1) / 3)

NEA2022 <- NEA2022 %>%
  mutate(steuncol_plot = (steuncol_RR - 1) / 3)

NEA2022 <- NEA2022 %>%
  mutate(psyveil_plot = (psyveil_RR - 1) / 4)

```



## Model4

```{r plot 4, echo=TRUE}
model4_bpred <- model4_b$predclass
NEA2022$model4_bpred <- model4_b$predclass
table(model4_b$predclass)
prop.table(table(model4_b$predclass)) * 100

vars <- c("bul_c_plot", "bul_s_plot", "int_c_plot", "int_s_plot",
          "vio_c_plot", "vio_s_plot", "sex_c_plot", "sex_s_plot",
          "conflict_col_plot", "conflict_leid_plot", 
          "steuncol_plot", "steunleid_plot", "psyveil_plot")

plot_data4 <- NEA2022 %>%
  pivot_longer(cols = all_of(vars), names_to = "indicator", values_to = "value") %>%
  group_by(model4_bpred, indicator) %>%
  summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    indicator   = factor(indicator, levels = vars),
    class_label = recode(as.character(model4_bpred), 
                         "1" = "1 (20.58%)", 
                         "2" = "2 (6.14%)", 
                         "3" = "3 (15.43%)", 
                         "4" = "4 (57.85%)")
  )%>% 
  mutate(class_label = factor(class_label,
                      levels = c("1 (20.58%)", "2 (6.14%)", "3 (15.43%)", "4 (57.85%)")))

indicator_labels <- c(
  "bul_c_plot"    = "Bullying C",
  "bul_s_plot"   = "Bullying S",
  "int_c_plot"       = "Intimidation C",
  "int_s_plot"      = "Intimidation S",
  "sex_c_plot"      = "Unwanted sexual attention C",
  "sex_s_plot"     = "Unwanted sexual attention S",
  "vio_c_plot"       = "Violence C",
  "vio_s_plot"      = "Violence S",
  "conflict_col_plot"  = "Conflict C",
  "conflict_leid_plot" = "Conflict S",
  "steuncol_plot"      = "Incivility C",
  "steunleid_plot"     = "Incivility S",
  "psyveil_plot"       = "Psychological unsafety"
)

ggplot(plot_data4, aes(x = indicator, y = mean_value,
                      color = class_label, group = class_label)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_discrete(labels = indicator_labels) +
  scale_y_continuous(breaks = seq(0, 1, 0.1),
                     limits = c(0, 1),
                     expand = c(0,0)) +
  scale_color_manual(
    values = c(
      "1 (20.58%)"   = "#0072B2",
      "2 (6.14%)"          = "#D55E00",
      "3 (15.43%)"   = "#CC79A7",
      "4 (57.85%)" = "#56B4E9"
    )
  ) +
  labs(x = NULL, y = "Mean score", color = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.text = element_text(size = 11)
  )

```

## Model 5

```{r plot 5, echo=TRUE}
model5_bpred <- model5_b$predclass
NEA2022$model5_bpred <- model5_b$predclass
table(model5_b$predclass)
prop.table(table(model5_b$predclass)) * 100

vars <- c("bul_c_plot", "bul_s_plot", "int_c_plot", "int_s_plot",
          "vio_c_plot", "vio_s_plot", "sex_c_plot", "sex_s_plot",
          "conflict_col_plot", "conflict_leid_plot", 
          "steuncol_plot", "steunleid_plot", "psyveil_plot")

plot_data5 <- NEA2022 %>%
  pivot_longer(cols = all_of(vars), names_to = "indicator", values_to = "value") %>%
  group_by(model5_bpred, indicator) %>%
  summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    indicator   = factor(indicator, levels = vars),
    class_label = recode(as.character(model5_bpred), 
                         "1" = "1 (3.16%)", 
                         "2" = "2 (57.54%)", 
                         "3" = "3 (5.34%)", 
                         "4" = "4 (13.46%)",
                         "5" = "5 (20.49%)")
  ) %>% 
  mutate(class_label = factor(class_label,
                      levels = c("1 (3.16%)", "2 (57.54%)", "3 (5.34%)", 
                                 "4 (13.46%)", "5 (20.49%)")))

indicator_labels <- c(
  "bul_c_plot"       = "Bullying C",
  "bul_s_plot"       = "Bullying S",
  "int_c_plot"       = "Intimidation C",
  "int_s_plot"       = "Intimidation S",
  "sex_c_plot"       = "Unwanted sexual attention C",
  "sex_s_plot"       = "Unwanted sexual attention S",
  "vio_c_plot"       = "Violence C",
  "vio_s_plot"       = "Violence S",
  "conflict_col_plot"  = "Conflict C",
  "conflict_leid_plot" = "Conflict S",
  "steuncol_plot"      = "Incivility C",
  "steunleid_plot"     = "Incivility S",
  "psyveil_plot"       = "Psychological unsafety"
)

ggplot(plot_data5, aes(x = indicator, y = mean_value,
                       color = class_label, group = class_label)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_discrete(labels = indicator_labels) +
  scale_y_continuous(breaks = seq(0, 1, 0.1),
                     limits = c(0, 1),
                     expand = c(0,0)) +
  scale_color_manual(
    values = c(
      "1 (3.16%)"   = "#D55E00",
      "2 (57.54%)"  = "#56B4E9",
      "3 (5.34%)"   = "#E69F00",
      "4 (13.46%)"  = "#CC79A7",
      "5 (20.49%)"  = "#0072B2"
    )
  ) +
  labs(x = NULL, y = "Mean score", color = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.text = element_text(size = 11)
  )

```


## Model6


```{r plot 6, echo=TRUE}
model6_bpred <- model6_b$predclass
NEA2022$model6_bpred <- model6_b$predclass
table(model6_b$predclass)
prop.table(table(model6_b$predclass)) * 100

vars <- c("bul_c_plot", "bul_s_plot", "int_c_plot", "int_s_plot",
          "vio_c_plot", "vio_s_plot", "sex_c_plot", "sex_s_plot",
          "conflict_col_plot", "conflict_leid_plot", 
          "steuncol_plot", "steunleid_plot", "psyveil_plot")

plot_data6 <- NEA2022 %>%
  pivot_longer(cols = all_of(vars), names_to = "indicator", values_to = "value") %>%
  group_by(model6_bpred, indicator) %>%
  summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    indicator   = factor(indicator, levels = vars),
    class_label = recode(as.character(model6_bpred), 
                         "1" = "1 (4.73%)", 
                         "2" = "2 (2.03%)", 
                         "3" = "3 (13.70%)", 
                         "4" = "4 (20.41%)",
                         "5" = "5 (57.37%)",
                         "6" = "6 (1.77%)")
  ) %>% 
  mutate(class_label = factor(class_label,
                      levels = c("1 (4.73%)", "2 (2.03%)", "3 (13.70%)", 
                                 "4 (20.41%)", "5 (57.37%)", "6 (1.77%)")))

indicator_labels <- c(
  "bul_c_plot"       = "Bullying C",
  "bul_s_plot"       = "Bullying S",
  "int_c_plot"       = "Intimidation C",
  "int_s_plot"       = "Intimidation S",
  "sex_c_plot"       = "Unwanted sexual attention C",
  "sex_s_plot"       = "Unwanted sexual attention S",
  "vio_c_plot"       = "Violence C",
  "vio_s_plot"       = "Violence S",
  "conflict_col_plot"  = "Conflict C",
  "conflict_leid_plot" = "Conflict S",
  "steuncol_plot"      = "Incivility C",
  "steunleid_plot"     = "Incivility S",
  "psyveil_plot"       = "Psychological unsafety"
)

ggplot(plot_data6, aes(x = indicator, y = mean_value,
                       color = class_label, group = class_label)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_discrete(labels = indicator_labels) +
  scale_y_continuous(breaks = seq(0, 1, 0.1),
                     limits = c(0, 1),
                     expand = c(0,0)) +
  scale_color_manual(
    values = c(
      "1 (4.73%)"   = "#E69F00",
      "2 (2.03%)"   = "#D55E00",
      "3 (13.70%)"  = "#CC79A7",
      "4 (20.41%)"  = "#0072B2",
      "5 (57.37%)"  = "#56B4E9",
      "6 (1.77%)"   = "#000000"
    )
  ) +
  labs(x = NULL, y = "Mean score", color = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.text = element_text(size = 11)
  )

```


## Model7

```{r plot 7, echo=TRUE}
model7_bpred <- model7_b$predclass
NEA2022$model7_bpred <- model7_b$predclass
table(model7_bpred)
prop.table(table(model7_b$predclass)) * 100

vars <- c("bul_c_plot", "bul_s_plot", "int_c_plot", "int_s_plot",
          "vio_c_plot", "vio_s_plot", "sex_c_plot", "sex_s_plot",
          "conflict_col_plot", "conflict_leid_plot", 
          "steuncol_plot", "steunleid_plot", "psyveil_plot")

plot_data7 <- NEA2022 %>%
  pivot_longer(cols = all_of(vars), names_to = "indicator", values_to = "value") %>%
  group_by(model7_bpred, indicator) %>%
  summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    indicator   = factor(indicator, levels = vars),
    class_label = recode(as.character(model7_bpred),
                         "1" = "Short-term conflict (6.48%)",
                         "2" = "Supervisor unsafety (1.99%)",
                         "3" = "Coworker unsafety (2.95%)",
                         "4" = "Unsafe social climate (10.41%)",
                         "5" = "Safe (56.00%)",
                         "6" = "Highly safe (20.36%)",
                         "7" = "Overall unsafe (1.81%)")
  ) %>%
  mutate(class_label = factor(class_label,
                              levels = c("Highly safe (20.36%)", 
                                         "Safe (56.00%)",
                                         "Short-term conflict (6.48%)", 
                                         "Unsafe social climate (10.41%)", 
                                         "Coworker unsafety (2.95%)", 
                                         "Supervisor unsafety (1.99%)", 
                                         "Overall unsafe (1.81%)")))

indicator_labels <- c(
  "bul_c_plot"    = "Bullying C",
  "bul_s_plot"   = "Bullying S",
  "int_c_plot"       = "Intimidation C",
  "int_s_plot"      = "Intimidation S",
  "sex_c_plot"      = "Unwanted sexual attention C",
  "sex_s_plot"     = "Unwanted sexual attention S",
  "vio_c_plot"       = "Violence C",
  "vio_s_plot"      = "Violence S",
  "conflict_col_plot"  = "Conflict C",
  "conflict_leid_plot" = "Conflict S",
  "steuncol_plot"      = "Incivility C",
  "steunleid_plot"     = "Incivility S",
  "psyveil_plot"       = "Psychological unsafety"
)

ggplot(plot_data7, aes(x = indicator, y = mean_value,
                      color = class_label, group = class_label)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_discrete(labels = indicator_labels) +
  scale_y_continuous(breaks = seq(0, 1, 0.1),
                     limits = c(0, 1),
                     expand = c(0,0)) +
  scale_color_manual(
    values = c(
      "Highly safe (20.36%)"   = "#0072B2",
      "Safe (56.00%)"          = "#56B4E9",
      "Short-term conflict (6.48%)"   = "#009E73",
      "Unsafe social climate (10.41%)" = "#CC79A7",
      "Coworker unsafety (2.95%)"     = "#E69F00",
      "Supervisor unsafety (1.99%)"   = "#D55E00",
      "Overall unsafe (1.81%)"        = "#000000" 
    )
  ) +
  labs(x = NULL, y = "Mean score", color = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.text = element_text(size = 11)
  )
```

## Model8


```{r plot 8, echo=TRUE}
model8_bpred <- model8_b$predclass
NEA2022$model8_bpred <- model8_b$predclass
table(model8_b$predclass)
prop.table(table(model8_b$predclass)) * 100

vars <- c("bul_c_plot", "bul_s_plot", "int_c_plot", "int_s_plot",
          "vio_c_plot", "vio_s_plot", "sex_c_plot", "sex_s_plot",
          "conflict_col_plot", "conflict_leid_plot", 
          "steuncol_plot", "steunleid_plot", "psyveil_plot")

plot_data8 <- NEA2022 %>%
  pivot_longer(cols = all_of(vars), names_to = "indicator", values_to = "value") %>%
  group_by(model8_bpred, indicator) %>%
  summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    indicator   = factor(indicator, levels = vars),
    class_label = recode(as.character(model8_bpred), 
                         "1" = "1 (20.43%)", 
                         "2" = "2 (1.75%)", 
                         "3" = "3 (6.41%)", 
                         "4" = "4 (55.64%)",
                         "5" = "5 (10.40%)",
                         "6" = "6 (2.76%)",
                         "7" = "7 (1.67%)",
                         "8" = "8 (0.94%)")
  ) %>% 
  mutate(class_label = factor(class_label,
                      levels = c("1 (20.43%)", "2 (1.75%)", "3 (6.41%)", 
                                 "4 (55.64%)", "5 (10.40%)", "6 (2.76%)", 
                                 "7 (1.67%)", "8 (0.94%)")))

indicator_labels <- c(
  "bul_c_plot"        = "Bullying C",
  "bul_s_plot"        = "Bullying S",
  "int_c_plot"        = "Intimidation C",
  "int_s_plot"        = "Intimidation S",
  "sex_c_plot"        = "Unwanted sexual attention C",
  "sex_s_plot"        = "Unwanted sexual attention S",
  "vio_c_plot"        = "Violence C",
  "vio_s_plot"        = "Violence S",
  "conflict_col_plot" = "Conflict C",
  "conflict_leid_plot"= "Conflict S",
  "steuncol_plot"     = "Incivility C",
  "steunleid_plot"    = "Incivility S",
  "psyveil_plot"      = "Psychological unsafety"
)

ggplot(plot_data8, aes(x = indicator, y = mean_value,
                       color = class_label, group = class_label)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_discrete(labels = indicator_labels) +
  scale_y_continuous(breaks = seq(0, 1, 0.1),
                     limits = c(0, 1),
                     expand = c(0,0)) +
  scale_color_manual(
    values = c(
      "1 (20.43%)" = "#0072B2",
      "2 (1.75%)"  = "#D55E00",
      "3 (6.41%)"  = "#009E73",
      "4 (55.64%)" = "#56B4E9",
      "5 (10.40%)" = "#CC79A7",
      "6 (2.76%)"  = "#E69F00",
      "7 (1.67%)"  = "#000000",
      "8 (0.94%)"  = "#F0E442"
    )
  ) +
  labs(x = NULL, y = "Mean score", color = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.text = element_text(size = 11)
  )
```


## Model9


```{r plot 9, echo=TRUE}
model9_bpred <- model9_b$predclass
NEA2022$model9_bpred <- model9_b$predclass
table(model9_b$predclass)
prop.table(table(model9_b$predclass)) * 100

vars <- c("bul_c_plot", "bul_s_plot", "int_c_plot", "int_s_plot",
          "vio_c_plot", "vio_s_plot", "sex_c_plot", "sex_s_plot",
          "conflict_col_plot", "conflict_leid_plot", 
          "steuncol_plot", "steunleid_plot", "psyveil_plot")

plot_data9 <- NEA2022 %>%
  pivot_longer(cols = all_of(vars), names_to = "indicator", values_to = "value") %>%
  group_by(model9_bpred, indicator) %>%
  summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  mutate(
    indicator   = factor(indicator, levels = vars),
    class_label = recode(as.character(model9_bpred), 
                         "1" = "1 (11.33%)", 
                         "2" = "2 (2.16%)", 
                         "3" = "3 (5.62%)", 
                         "4" = "4 (1.63%)",
                         "5" = "5 (0.38%)",
                         "6" = "6 (1.60%)",
                         "7" = "7 (55.82%)",
                         "8" = "8 (20.40%)",
                         "9" = "9 (1.06%)")
  ) %>% 
  mutate(class_label = factor(class_label,
                      levels = c("1 (11.33%)", "2 (2.16%)", "3 (5.62%)", "4 (1.63%)",
                                 "5 (0.38%)", "6 (1.60%)", "7 (55.82%)", 
                                 "8 (20.40%)", "9 (1.06%)")))

indicator_labels <- c(
  "bul_c_plot"        = "Bullying C",
  "bul_s_plot"        = "Bullying S",
  "int_c_plot"        = "Intimidation C",
  "int_s_plot"        = "Intimidation S",
  "sex_c_plot"        = "Unwanted sexual attention C",
  "sex_s_plot"        = "Unwanted sexual attention S",
  "vio_c_plot"        = "Violence C",
  "vio_s_plot"        = "Violence S",
  "conflict_col_plot" = "Conflict C",
  "conflict_leid_plot"= "Conflict S",
  "steuncol_plot"     = "Incivility C",
  "steunleid_plot"    = "Incivility S",
  "psyveil_plot"      = "Psychological unsafety"
)

ggplot(plot_data9, aes(x = indicator, y = mean_value,
                       color = class_label, group = class_label)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_discrete(labels = indicator_labels) +
  scale_y_continuous(breaks = seq(0, 1, 0.1),
                     limits = c(0, 1),
                     expand = c(0,0)) +
  scale_color_manual(
    values = c(
      "1 (11.33%)" = "#CC79A7",
      "2 (2.16%)"  = "#E69F00",
      "3 (5.62%)"  = "#009E73",
      "4 (1.63%)"  = "#000000",
      "5 (0.38%)"  = "#999999",
      "6 (1.60%)"  = "#D55E00",
      "7 (55.82%)" = "#56B4E9",
      "8 (20.40%)" = "#0072B2",
      "9 (1.06%)"  = "#F0E442"
    )
  ) +
  labs(x = NULL, y = "Mean score", color = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.text = element_text(size = 11)
  )
```
