---
title: "Multinomial"
output: html_document
date: "2025-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading packages, warning=FALSE, results='hide', message=FALSE}
library("formatR")
library("foreign")
library("ggplot2")
library("lme4")
library("poLCA")
library("reprex")
library("tidyr")
library("klippy")
library("dplyr")
library("haven")
library("psych")
library("Matrix")
library("lme4")
library("merTools")
library("sjPlot")
library("glmmTMB")
library("foreign")
library("gt")
library("tibble")
library("dplyr")
library("brms")
```


<br><br> **Loading the data**

```{r loading data, warning=FALSE, message=FALSE}
NEA2022 <- readRDS("data/processed/LCAfinal.rds")

set.seed(123)
```


```{r test, warning=FALSE, message=FALSE}
which(duplicated(names(NEA2022)))
names(NEA2022)[duplicated(names(NEA2022))]

grep("leeftijd", names(NEA2022), value = TRUE)
```

<br><br>

```{r factor}
table(NEA2022$model7_emppred)
NEA2022$pred_7_f <- as.factor(NEA2022$model7_emppred)
NEA2022$pred_7_f <- relevel(NEA2022$pred_7_f, ref = "3")
table(NEA2022$pred_7_f)
```

<br><br>

# Multinomial multilevel (ref = highly safe)


<br><br>

## Model0

<br><br>

```{r, warning=FALSE}
attach(NEA2022)
data_multi <- data.frame(gender_v, migration_eu, migration_noeu, 
    education_laag, education_middel, leeftijd_35_55, leeftijd_55_75, pred_7_f, intersections)
attach(data_multi)
```


```{r multinomial model0, cache=TRUE}
brm_emp7_0 <- brm(
  formula = pred_7_f ~ 1 + (1 | intersections),
  data = data_multi,
  family = categorical(),
  chains = 4, cores = 2, iter = 2000
)

summary(brm_emp7_0)
```


<br><br>

## Model1

<br><br>

```{r multinomial model1, cache=TRUE}

brm_emp7_1 <- brm(
  formula = pred_7_f ~ gender_v + migration_eu + migration_noeu + 
    education_laag + education_middel + leeftijd_35_55 + leeftijd_55_75 +
    (1 | intersections),
  data = data_multi,
  family = categorical(),
  chains = 4, cores = 2, iter = 2000
)

summary(brm_emp7_1)
```
<br><br>

## ICC

<br><br>

```{r}
#Overall unsafety (6)

cat("ICC model0: ", (0.54*0.54)/((0.54*0.54)+3.29), "\n",
    "ICC final: ", (0.24*0.24)/((0.24*0.24)+3.29), "\n",
    "PCV: ", (0.2916-0.0576)/0.2916, "\n")

#Supervisor unsafety (4)

cat("ICC model0: ", (0.31*0.31)/((0.31*0.31)+3.29), "\n",
    "ICC final: ", (0.16*0.16)/((0.16*0.16)+3.29), "\n",
    "PCV: ", (0.0961-0.0256)/0.0961, "\n")

#Coworker unsafety (7)

cat("ICC model0: ", (0.25*0.25)/((0.25*0.25)+3.29), "\n",
    "ICC final: ", (0.12*0.12)/((0.12*0.12)+3.29), "\n",
    "PCV: ", (0.0625-0.0144)/0.0625, "\n")

#Unsafe social climate (5)

cat("ICC model0: ", (0.27*0.27)/((0.27*0.27)+3.29), "\n",
    "ICC final: ", (0.05*0.05)/((0.05*0.05)+3.29), "\n",
    "PCV: ", (0.0729-0.0025)/0.0729, "\n")

#Short-term conflict (1)

cat("ICC model0: ", (0.30*0.30)/((0.30*0.30)+3.29), "\n",
    "ICC final: ", (0.13*0.13)/((0.13*0.13)+3.29), "\n",
    "PCV: ", (0.09-0.0169)/0.09, "\n")

#Safe (2)

cat("ICC model0: ", (0.14*0.14)/((0.14*0.14)+3.29), "\n",
    "ICC final: ", (0.05*0.05)/((0.05*0.05)+3.29), "\n",
    "PCV: ", (0.0169-0.0025)/0.0169, "\n")
```
