---
title: "Plotjes na.rm = true"
output: html_document
date: "2025-04-29"
---
Model na.rm = TRUE


```{r}
NEAfinal <-read.spss("data/processed/NEAfinal.sav", use.value.labels = T, to.data.frame = T)
```

```{r}
NEA28262 <- NEAfinal %>%
  filter(
    !is.na(pesten_col) &
    !is.na(pesten_leid) &
    !is.na(intimidation_col) &
    !is.na(intimidation_leid) &
    !is.na(geweld_col) &
    !is.na(geweld_leid) &
    !is.na(seks_col) &
    !is.na(seks_leid) &
    !is.na(conflict_col) &
    !is.na(conflict_leid) &
    !is.na(steunleid_RR) &
    !is.na(steuncol_RR) &
    !is.na(psyveil_RR)
  )
```


```{r}
#pesten collega's
table(NEA28262$pesten_col)


NEA28262 <- NEA28262 %>%
  mutate(pesten_col_plot = recode(pesten_col, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$pesten_col_plot)
summary(NEA28262$pesten_col_plot)

```

```{r}
#pesten leidinggevenden
table(NEA28262$pesten_leid)


NEA28262 <- NEA28262 %>%
  mutate(pesten_leid_plot = recode(pesten_leid, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$pesten_leid_plot)

```

```{r}
#intimidatie collega's
table(NEA28262$intimidation_col)


NEA28262 <- NEA28262 %>%
  mutate(int_col_plot = recode(intimidation_col, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$int_col_plot)

```

```{r}
#intimidatie leidinggevenden
table(NEA28262$intimidation_leid)

NEA28262 <- NEA28262 %>%
  mutate(int_leid_plot = recode(intimidation_leid, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$int_leid_plot)
```

```{r}
#fysiek geweld collega's
table(NEA28262$geweld_col)

NEA28262 <- NEA28262 %>%
  mutate(gew_col_plot = recode(geweld_col, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$gew_col_plot)
```

```{r}
#fysiek geweld leidinggevenden
table(NEA28262$geweld_leid)

NEA28262 <- NEA28262 %>%
  mutate(gew_leid_plot = recode(geweld_leid, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$gew_leid_plot)
```

```{r}
#ongewenste seksuele aandacht collega's
table(NEA28262$seks_col)

NEA28262 <- NEA28262 %>%
  mutate(seks_col_plot = recode(seks_col, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$seks_col_plot)
```

```{r}
#ongewenste seksuele aandacht leidinggevenden
table(NEA28262$seks_leid)

NEA28262 <- NEA28262 %>%
  mutate(seks_leid_plot = recode(seks_leid, `1` = 0, `2` = 0.33, `3` = 0.67, `4` = 1))
table(NEA28262$seks_leid_plot)
```

```{r}
#conflict collega
table(NEA28262$conflict_col)
NEA28262 <- NEA28262 %>%
  mutate(conflict_col_plot = recode(conflict_col, `1` = 0, `2` = 0.50, `3` = 1))
table(NEA28262$conflict_col_plot)
```

```{r}
#conflict leidinggevende
table(NEA28262$conflict_leid)
NEA28262 <- NEA28262 %>%
  mutate(conflict_leid_plot = recode(conflict_leid, `1` = 0, `2` = 0.50, `3` = 1))
table(NEA28262$conflict_leid_plot)
```

```{r}
#conflict collega
table(NEA28262$conflict_werk)
NEA28262 <- NEA28262 %>%
  mutate(conflict_werk_plot = recode(conflict_werk, `1` = 0, `2` = 0.50, `3` = 1))
table(NEA28262$conflict_werk_plot)
```

```{r}
NEA28262$steunleid_scale <- rowMeans(NEA28262[c("steunleid_aandacht", "steunleid_welzijn")], na.rm = TRUE)
summarytools::freq(NEA28262$steunleid_scale)
summarytools::freq(NEA28262$afl_socs)

NEA28262 <- NEA28262 %>%
  mutate(steunleid_RR = case_when(
    steunleid_scale %in% c(1) ~ 1,
    steunleid_scale %in% c(1.5, 2) ~ 2,
    steunleid_scale %in% c(2.5, 3) ~ 3,
    steunleid_scale %in% c(3.5, 4) ~ 4,
    TRUE ~ NA_real_
  ))

summarytools::freq(NEA28262$steunleid_RR)

NEA28262 <- NEA28262 %>%
  mutate(steunleid_plot3 = (steunleid_RR - 1) / 3)

summarytools::freq(NEA28262$steunleid_plot3)

```
```{r}
NEA28262$steuncol_scale <- rowMeans(NEA28262[c("steuncol_belang", "steuncol_vriendelijk")], na.rm = TRUE)
summarytools::freq(NEA28262$steuncol_scale)
summarytools::freq(NEA28262$afl_so_2)

NEA28262 <- NEA28262 %>%
  mutate(steuncol_RR = case_when(
    steuncol_scale %in% c(1) ~ 1,
    steuncol_scale %in% c(1.5, 2) ~ 2,
    steuncol_scale %in% c(2.5, 3) ~ 3,
    steuncol_scale %in% c(3.5, 4) ~ 4,
    TRUE ~ NA_real_
  ))

summarytools::freq(NEA28262$steuncol_RR)

NEA28262 <- NEA28262 %>%
  mutate(steuncol_plot3 = (steuncol_RR - 1) / 3)

summarytools::freq(NEA28262$steuncol_plot3)
```
```{r}
NEA28262$psyveil_scale <- rowMeans(NEA28262[c("psyveil_last", "psyveil_hulp", "psyveil_fout")], na.rm = TRUE)

summarytools::freq(NEA28262$psyveil_scale)

NEA28262$psyveil_R <- as.numeric(factor(NEA28262$psyveil_scale))

summarytools::freq(NEA28262$psyveil_R)

NEA28262$psyveil_R[NEA28262$psyveil_R == "18"] <- NA


summarytools::freq(NEA28262$psyveil_scale)
summarytools::freq(NEA28262$psyveil_R)

NEA28262 <- NEA28262 %>%
  mutate(psyveil_RR = case_when(
    psyveil_R %in% c(1, 2) ~ 1,
    psyveil_R %in% c(3, 4, 5, 6) ~ 2,
    psyveil_R %in% c(7, 8, 9, 10) ~ 3,
    psyveil_R %in% c(11, 12, 13, 14) ~ 4,
    psyveil_R %in% c(15, 16, 17) ~ 5,
    TRUE ~ NA_real_
  ))
summarytools::freq(NEA28262$psyveil_scale)
summarytools::freq(NEA28262$psyveil_RR)

NEA28262 <- NEA28262 %>%
  mutate(psyveil_plot3 = (psyveil_RR - 1) / 4)

summarytools::freq(NEA28262$psyveil_plot3)

```


```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_2 <- model2m$predclass
table(NEA28262$classm_2)
```
```{r echo=FALSE, message=FALSE, warning=FALSE, include=TRUE, results='hide'}
NEA28262$classm_3 <- model3m$predclass
table(NEA28262$classm_3)
```
```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_4 <- model4m$predclass
table(NEA28262$classm_4)
```
```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_5 <- model5m$predclass
table(NEA28262$classm_5)
```
```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_6 <- model6m$predclass
table(NEA28262$classm_6)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_7 <- model7m$predclass
table(NEA28262$classm_7)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_8 <- model8m$predclass
table(NEA28262$classm_8)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_9 <- model9m$predclass
table(NEA28262$classm_9)
```

```{r, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA28262$classm_10 <- model10m$predclass
table(NEA28262$classm_10)
```


```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_2, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_2, mean, na.rm = TRUE)
```


Class 3

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_3, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_3, mean, na.rm = TRUE)
```

Class 4

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_4, mean, na.rm = TRUE)
```


```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_4, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_4, mean, na.rm = TRUE)
```

Class 5

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_werk_plot, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_5, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_5, mean, na.rm = TRUE)
```

Class 6

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_werk_plot, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_6, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_6, mean, na.rm = TRUE)
```

Class 7

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_werk_plot, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_7, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_7, mean, na.rm = TRUE)
```

Class 8

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_werk_plot, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_8, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_8, mean, na.rm = TRUE)
```

Class 9

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```
```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_9, mean, na.rm = TRUE)
```
```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_9, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_9, mean, na.rm = TRUE)
```
Class 10

```{r}
tapply(NEA28262$pesten_col_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$pesten_leid_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$int_col_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```
```{r}
tapply(NEA28262$int_leid_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_col_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$gew_leid_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_col_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$seks_leid_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_col_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$conflict_leid_plot, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steunleid_plot3, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$steuncol_plot3, NEA28262$classm_10, mean, na.rm = TRUE)
```

```{r}
tapply(NEA28262$psyveil_plot3, NEA28262$classm_10, mean, na.rm = TRUE)
```
