---
title: "Recoding variables"
output: html_document
date: "2025-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, echo = TRUE)
```


```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```



```{r klippy5, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


```{r}
library("formatR")
library("foreign")
library("ggplot2")
library("lme4")
library("poLCA")
library("reprex")
library("tidyr")
library("klippy")
library("dplyr")
library("haven")
```

```{r klippy6, echo=FALSE, include=TRUE, results='hide', warning=FALSE, message=FALSE}
NEA2022 <-read.spss("data/processed/Data 2022 cleaned.sav", use.value.labels = T, to.data.frame = T)
attach(NEA2022)

#NEA20142022 <-read.spss("data/raw/Data 2014-2022.sav", use.value.labels = T, to.data.frame = T)
```


```{r}
#pesten collega's
table(NEA2022$afl_pe_1)

NEA2022$pesten_col <- as.numeric(NEA2022$afl_pe_1)

table(NEA2022$pesten_col)

NEA2022 <- NEA2022 %>%
  mutate(pesten_col = recode(pesten_col, `4` = 1, `1` = 2, `2` = 3, `3` = 4))

table(NEA2022$pesten_col)

```

```{r}
#pesten leidinggevenden
table(NEA2022$afl_pe_2)

NEA2022$pesten_leid <- as.numeric(NEA2022$afl_pe_2)

table(NEA2022$pesten_leid)

NEA2022 <- NEA2022 %>%
  mutate(pesten_leid = recode(pesten_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$pesten_leid)
```

```{r}
#intimidatie collega's
table(NEA2022$afl_be_1)

NEA2022$intimidation_col <- as.numeric(NEA2022$afl_be_1)

table(NEA2022$intimidation_col)

NEA2022 <- NEA2022 %>%
  mutate(intimidation_col = recode(intimidation_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$intimidation_col)

```

```{r}
#intimidatie leidinggevenden
table(NEA2022$afl_be_2)

NEA2022$intimidation_leid <- as.numeric(NEA2022$afl_be_2)

table(NEA2022$intimidation_leid)

NEA2022 <- NEA2022 %>%
  mutate(intimidation_leid = recode(intimidation_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$intimidation_leid)

```

```{r}
#fysiek geweld collega's
table(NEA2022$afl_ge_3)

NEA2022$geweld_col <- as.numeric(NEA2022$afl_ge_3)

table(NEA2022$geweld_col)

NEA2022 <- NEA2022 %>%
  mutate(geweld_col = recode(geweld_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$geweld_col)

```

```{r}
#fysiek geweld leidinggevenden
table(NEA2022$afl_ge_4)

NEA2022$geweld_leid <- as.numeric(NEA2022$afl_ge_4)

table(NEA2022$geweld_leid)

NEA2022 <- NEA2022 %>%
  mutate(geweld_leid = recode(geweld_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$geweld_leid)
```

```{r}
#ongewenste seksuele aandacht collega's
table(NEA2022$afl_se_1)

NEA2022$seks_col <- as.numeric(NEA2022$afl_se_1)

table(NEA2022$seks_col)

NEA2022 <- NEA2022 %>%
  mutate(seks_col = recode(seks_col, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$seks_col)
```

```{r}
#ongewenste seksuele aandacht leidinggevenden
table(NEA2022$afl_se_2)

NEA2022$seks_leid <- as.numeric(NEA2022$afl_se_2)

table(NEA2022$seks_leid)

NEA2022 <- NEA2022 %>%
  mutate(seks_leid = recode(seks_leid, `1` = 2, `2` = 3, `3` = 4, `4` = 1))

table(NEA2022$seks_leid)

```

```{r}
#conflict collega
table(NEA2022$conflict)

NEA2022$conflict_col <- as.numeric(NEA2022$conflict)

table(NEA2022$conflict_col)
```

```{r}
#conflict leidinggevende
table(NEA2022$confli_1)

NEA2022$conflict_leid <- as.numeric(NEA2022$confli_1)

table(NEA2022$conflict_leid)
```

```{r}
#conflict werkgever
table(NEA2022$confli_2)

NEA2022$conflict_werk <- as.numeric(NEA2022$confli_2)

table(NEA2022$conflict_werk)
```

```{r}
#conflict werkgever
table(NEA2022$confli_2)

NEA2022$conflict_werk <- as.numeric(NEA2022$confli_2)

table(NEA2022$conflict_werk)
```

```{r}
#sociale steun leidinggevende: mijn leidinggevende heeft oog voor het welzijn van de medewerkers
table(NEA2022$leiding_)

NEA2022$leiding_[NEA2022$leiding_ == "nvt"] <- NA

NEA2022$steunleid_welzijn <- as.numeric(NEA2022$leiding_)

table(NEA2022$steunleid_welzijn)

NEA2022 <- NEA2022 %>%
  mutate(steunleid_welzijn = recode(steunleid_welzijn, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

table(NEA2022$steunleid_welzijn)
```

```{r}
#sociale steun leidinggevende: mijn leidinggevende besteedt aandacht aan wat ik zeg
table(NEA2022$leidin_1)

NEA2022$leidin_1[NEA2022$leidin_1 == "nvt"] <- NA

NEA2022$steunleid_aandacht <- as.numeric(NEA2022$leidin_1)

table(NEA2022$steunleid_aandacht)

NEA2022 <- NEA2022 %>%
  mutate(steunleid_aandacht = recode(steunleid_aandacht, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

table(NEA2022$steunleid_aandacht)
```

```{r}
#sociale steun collega's: mijn collega's hebben persoonlijke belangstelling voor me
table(NEA2022$collega_)

NEA2022$collega_[NEA2022$collega_ == "nvt"] <- NA

NEA2022$steuncol_belang <- as.numeric(NEA2022$collega_)

table(NEA2022$steuncol_belang)

NEA2022 <- NEA2022 %>%
  mutate(steuncol_belang = recode(steuncol_belang, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

table(NEA2022$steuncol_belang)
```

```{r}
#sociale steun collega's: mijn collega's zijn vriendelijk
table(NEA2022$colleg_1)

NEA2022$colleg_1[NEA2022$colleg_1 == "nvt"] <- NA

NEA2022$steuncol_vriendelijk <- as.numeric(NEA2022$colleg_1)

table(NEA2022$steuncol_vriendelijk)

NEA2022 <- NEA2022 %>%
  mutate(steuncol_vriendelijk = recode(steuncol_vriendelijk, `1` = 4, `2` = 3, `3` = 2, `4` = 1))

table(NEA2022$steuncol_vriendelijk)
```

```{r}
#Psychologische veiligheid: op mijn werk kun je lastige kwesties naar voren brengen
table(NEA2022$psyveil_)

NEA2022$psyveil_last <- as.numeric(NEA2022$psyveil_)

table(NEA2022$psyveil_last)
```

```{r}
#Psychologische veiligheid: op mijn werk ik het gemakkelijk om hulp te vragen
table(NEA2022$psyvei_1)

NEA2022$psyveil_hulp <- as.numeric(NEA2022$psyvei_1)

table(NEA2022$psyveil_hulp)
```

```{r}
#Psychologische veiligheid: op mijn werk is het niet erg om een fout te maken
table(NEA2022$psyvei_2)

NEA2022$psyveil_fout <- as.numeric(NEA2022$psyvei_2)

table(NEA2022$psyveil_fout)
```

```{r}
NEA2022_clust1 <- NEA2022 %>%
  filter(se_clust == 1)
```
